import { openWorkspaceStorageOrigin } from '../../browser-evidence';
import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from '../../browser-evidence';
import { installImportedRuntime, readWalletRuntimeFixture } from '../../wallet/fixtures/wallet-runtime-test-helpers';
import { installOpsOwnerMetadata } from './ops-owner-test-helpers';

test('owner unlock rejects another wallet, protects secrets, and revokes a cached owner lane on lock and expiry', { tag: '@resilience' }, async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  await page.clock.install();
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  await installOpsOwnerMetadata(page, fixture);
  await page.goto('/__app/ops/entity-workspace#settings');
  await page.getByRole('button', { name: 'Owner locked', exact: true }).click();
  const form = page.getByRole('form', { name: 'Unlock Runtime owner' });
  const seed = form.getByLabel('Owner wallet seed phrase');
  await seed.fill('abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about');
  await form.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(form.getByRole('alert')).toHaveText('RUNTIME_UNLOCK_SEED_MISMATCH');
  await screenshotEvidence(page, testInfo, 'ops-owner-wrong-wallet');
  await seed.fill(fixture.walletSeed);
  await form.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Owner unlocked', exact: true })).toBeVisible();
  const stored = await page.evaluate(() => localStorage.getItem('xln-vaults'));
  expect(stored).toContain('protectedSecrets');
  expect(stored).not.toContain(fixture.walletSeed);
  expect(stored).not.toContain('"seed"');
  await screenshotEvidence(page, testInfo, 'ops-owner-unlocked');
  await page.getByRole('button', { name: 'Owner unlocked', exact: true }).click();
  const name = page.getByTestId('settings-profile-name-input');
  const save = page.getByTestId('settings-profile-save');
  await name.fill(`Owner lease ${testInfo.project.name}`);
  await save.click();
  await expect(page.getByTestId('settings-profile-status')).toHaveText('Profile committed to the selected Entity.');
  await page.getByRole('button', { name: 'Owner unlocked', exact: true }).click();
  await form.getByRole('button', { name: 'Lock owner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Owner locked', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Owner locked', exact: true }).click();
  await name.fill('Must not commit after lock');
  await save.click();
  await expect(page.getByTestId('settings-profile-status')).toContainText('RUNTIME_LOCKED');
  await screenshotEvidence(page, testInfo, 'ops-owner-locked-command');
  await page.getByRole('button', { name: 'Owner locked', exact: true }).click();
  await seed.fill(fixture.walletSeed);
  await form.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Owner unlocked', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Owner unlocked', exact: true }).click();
  await page.clock.fastForward(601_000);
  await expect(page.getByRole('button', { name: 'Owner locked', exact: true })).toBeVisible();
  await name.fill('Must not commit after expiry');
  await save.click();
  await expect(page.getByTestId('settings-profile-status')).toContainText(/RUNTIME_LOCKED|VAULT_UNLOCK_EXPIRED/);
  await expect(page.getByTestId('entity-workspace-shell')).toHaveAttribute('data-runtime-id', fixture.runtimeId);
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-owner-expired');
  expectNoBrowserErrors(errors);
});
