import type { SurfaceId } from './surfaces';

export type CapabilityStatus = 'unstarted' | 'in_progress' | 'implemented' | 'verified' | 'blocked';

export type CapabilityDefinition = Readonly<{
  id: string;
  owner: SurfaceId;
  routes: readonly `/${string}`[];
  currentSources: readonly string[];
  behavior: readonly string[];
  status: CapabilityStatus;
}>;

export const CAPABILITIES = [
  {
    id: 'site-public-information',
    owner: 'site',
    routes: ['/', '/install', '/rcpan', '/releases', '/reviews', '/unicast', '/market-cap'],
    currentSources: [
      'frontend/src/routes/+page.svelte',
      'frontend/src/routes/install/+page.svelte',
      'frontend/apps/site/src/landing-page.tsx',
      'frontend/apps/site/src/install-page.tsx',
      'frontend/apps/site/src/rcpan/rcpan-page.tsx',
      'frontend/apps/site/src/unicast/unicast-page.tsx',
      'frontend/apps/site/src/releases/releases-page.tsx',
      'frontend/apps/site/src/reviews-page.tsx',
      'frontend/apps/site/src/market-cap-page.tsx',
      'frontend/packages/ui/src/content/market-cap-page-model.ts',
      'frontend/packages/ui/src/releases/release-catalog.ts',
      'frontend/packages/ui/src/releases/release-chart.ts',
      'frontend/packages/ui/src/releases/release-signature.ts',
      'frontend/packages/ui/src/content/reviews-model.ts',
      'frontend/packages/ui/src/rcpan/microscope/microscope-model.ts',
      'frontend/packages/ui/src/rcpan/microscope/microscope-playground.ts',
      'frontend/packages/ui/src/rcpan/microscope/microscope-timeline.ts',
    ],
    behavior: ['public navigation', 'install detection', 'deterministic RCPAN dispute microscope', 'broadcast/unicast scale visualization', 'verified release ledger', 'AI review prompt slideshow', 'live market-cap data'],
    status: 'implemented',
  },
  {
    id: 'docs-reader',
    owner: 'docs',
    routes: ['/docs'],
    currentSources: [
      'frontend/src/routes/docs/+page.svelte',
      'frontend/packages/ui/src/content/docs-page-model.ts',
      'frontend/packages/ui/src/safe-markdown.ts',
      'frontend/packages/runtime-client/src/boundary.ts',
      'frontend/apps/docs/src/docs-app.tsx',
      'frontend/scripts/docs/docs-catalog.js',
    ],
    behavior: ['catalog navigation and search', 'live/archive scope', 'safe Markdown rendering', 'deep links, anchors, and history', 'deterministic docs and llms outputs'],
    status: 'implemented',
  },
  {
    id: 'wallet-shell-and-identity',
    owner: 'wallet',
    routes: ['/app', '/address', '/testnet'],
    currentSources: [
      'frontend/packages/browser/src/runtime/wallet-boot-lifecycle.ts',
      'frontend/packages/browser/src/wallet/wallet-onboarding.ts',
      'frontend/packages/browser/src/wallet/wallet-formation.ts',
      'frontend/packages/browser/src/identity/wallet-brainvault-finalization.ts',
      'frontend/packages/browser/src/identity/wallet-brainvault-material-session.ts',
      'frontend/packages/browser/src/identity/wallet-brainvault-opening.ts',
      'frontend/packages/browser/src/identity/wallet-brainvault-worker-resilience.ts',
      'frontend/packages/browser/src/identity/wallet-brainvault-worker-scheduling.ts',
      'frontend/packages/browser/src/identity/wallet-brainvault-worker-validation.ts',
      'frontend/packages/browser/src/wallet-deploy-version.ts',
      'frontend/packages/browser/src/identity/wallet-identity-entry.ts',
      'frontend/packages/browser/src/identity/wallet-node-brainvault-validation.ts',
      'frontend/packages/browser/src/identity/wallet-node-mnemonic-reveal.ts',
      'frontend/packages/browser/src/recovery/wallet-recovery-choice.ts',
      'frontend/packages/browser/src/recovery/wallet-recovery-discovery.ts',
      'frontend/packages/browser/src/recovery/wallet-recovery-rehearsal.ts',
      'frontend/packages/browser/src/recovery/wallet-recovery-selection-session.ts',
      'frontend/packages/browser/src/runtime/wallet-runtime-bootstrap.ts',
      'frontend/packages/browser/src/runtime/wallet-runtime-consent.ts',
      'frontend/packages/browser/src/runtime/wallet-runtime-opening.ts',
      'frontend/packages/browser/src/runtime/wallet-runtime-preferences.ts',
      'frontend/packages/browser/src/wallet-shell-state.ts',
      'frontend/packages/browser/src/wallet/wallet-vault-storage.ts',
      'frontend/packages/ui/src/demo-accounts.ts',
      'frontend/packages/ui/src/runtime-creation-model.ts',
      'frontend/src/lib/components/Views/RuntimeCreation.svelte',
      'frontend/src/routes/app/+layout.svelte',
      'frontend/src/routes/app/+page.svelte',
      'frontend/src/routes/address/+page.svelte',
      'frontend/src/routes/testnet/+page.svelte',
      'frontend/apps/wallet/src/address/wallet-address-model.ts',
      'frontend/apps/wallet/src/address/wallet-address-runtime-affinity.ts',
      'frontend/apps/wallet/src/address/wallet-address-source.ts',
      'frontend/apps/wallet/src/address/wallet-address.tsx',
      'frontend/apps/wallet/src/identity/identity-brainvault-progress.tsx',
      'frontend/apps/wallet/src/identity/identity-entry-form.tsx',
      'frontend/apps/wallet/src/testnet/testnet-page.tsx',
      'frontend/bridges/wallet/brainvault/wallet-brainvault-browser-derivation.ts',
      'frontend/bridges/wallet/brainvault/wallet-brainvault-material-finalization.ts',
      'frontend/bridges/wallet/brainvault/wallet-brainvault-worker-runtime.ts',
      'frontend/bridges/wallet/wallet-canonical-vault-runtime.ts',
      'frontend/config/wallet-flow-audit.ts',
    ],
    behavior: [
      'boot and shell',
      'deterministic browser BrainVault finalization decisions',
      'canonical browser BrainVault worker derivation with bridge-held exact-once secret material',
      'deterministic browser BrainVault worker sizing and resilience decisions',
      'deterministic browser BrainVault retry, dispatch, and worker-scaling decisions',
      'validated browser BrainVault worker messages and shard completions',
      'generation-safe local and remote boot sequencing',
      'validated deploy-version persistence, reset, and recovery decisions',
      'canonical identity-mode selection, sensitive-field clearing, and keyboard navigation',
      'deterministic node BrainVault access, progress, result, and timing validation',
      'generation-safe node mnemonic reveal coordination',
      'deterministic recovery candidate selection, merge ordering, and continuation',
      'generation-safe recovery discovery coordination',
      'verified mnemonic recovery-rehearsal transitions and reset policy',
      'exact-once transient recovery authorization and canonical React restore',
      'ordered local-pairing, remote-import, and consent bootstrap',
      'validated remote consent and embedded cancellation ordering',
      'deterministic local unlock and Runtime creation planning',
      'deterministic Runtime preference decoding and serialization',
      'framework-neutral wallet shell phase precedence',
      'identity selection',
      'onboarding and settings',
      'React-owned public Entity directory and selected-Runtime detail projection',
      'testnet launcher and disposable identities',
    ],
    status: 'implemented',
  },
  {
    id: 'wallet-browser-lifecycle',
    owner: 'wallet',
    routes: ['/app', '/testnet'],
    currentSources: [
      'frontend/packages/browser/src/active-tab-lock.ts',
      'frontend/packages/browser/src/runtime/wallet-runtime-suspension.ts',
      'frontend/packages/browser/src/runtime/session/browser-runtime-reset.ts',
      'frontend/packages/browser/src/hard-reset-request.ts',
      'frontend/src/lib/utils/control/resetEverything.ts',
    ],
    behavior: [
      'validated destructive reset',
      'cross-tab reset notification',
      'exclusive cross-tab Runtime ownership and quiesced takeover',
      'storage, cache, and service-worker cleanup',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-runtime-discovery',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/packages/browser/src/runtime/session/runtime-adapter-session.ts',
      'frontend/packages/browser/src/runtime/session/runtime-module-loader.ts',
      'frontend/packages/browser/src/runtime/wallet-embedded-runtime-session.ts',
      'frontend/packages/runtime-client/src/runtime/runtime-adapter-activation.ts',
      'frontend/packages/runtime-client/src/runtime/runtime-handle.ts',
      'frontend/packages/runtime-client/src/runtime/remote-runtime-request.ts',
      'frontend/packages/browser/src/runtime/session/remote-runtime-import.ts',
      'frontend/packages/runtime-client/src/runtime/query/runtime-query-client.ts',
      'frontend/packages/runtime-client/src/runtime/query/runtime-query-observer.ts',
      'frontend/packages/runtime-client/src/runtime/runtime-selection.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-catchup.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-loader.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-model.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-projections.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-publication.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-refresh.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-selection.ts',
      'frontend/packages/runtime-client/src/runtime/view/runtime-view-state.ts',
      'frontend/packages/runtime-client/src/runtime/ws-url.ts',
      'frontend/packages/runtime-client/src/runtime/runtime-failure.ts',
      'frontend/apps/wallet/src/app-shell.tsx',
      'frontend/apps/wallet/src/app-shell-model.ts',
      'frontend/bridges/runtime/browser-runtime-adapter.ts',
      'frontend/bridges/runtime/browser-runtime-bootstrap.ts',
      'frontend/apps/wallet/src/runtime/wallet-embedded-runtime.ts',
      'frontend/apps/wallet/src/identity/identity-onboarding.tsx',
      'frontend/apps/wallet/src/identity/identity-onboarding-model.ts',
      'frontend/apps/wallet/src/identity/identity-recovery.tsx',
      'frontend/apps/wallet/src/onboarding/wallet-identity-opening.ts',
      'frontend/apps/wallet/src/settings/wallet-settings.tsx',
      'frontend/apps/wallet/src/settings/wallet-settings-model.ts',
      'frontend/apps/wallet/src/diagnostics/wallet-diagnostics.tsx',
      'frontend/apps/wallet/src/diagnostics/wallet-diagnostics-model.ts',
      'frontend/apps/wallet/src/financial-health/wallet-financial-health-source.ts',
      'frontend/apps/wallet/src/address/wallet-address-runtime-affinity.ts',
      'frontend/apps/wallet/src/runtime/wallet-runtime-read-boundary.ts',
      'frontend/apps/wallet/src/runtime/wallet-runtime-scope.tsx',
      'frontend/packages/browser/src/qrcode.d.ts',
      'frontend/src/lib/utils/runtime/runtimeConnection.ts',
    ],
    behavior: [
      'Runtime discovery',
      'validated hash bootstrap and query rejection',
      'tab-confined Runtime authority and rollback-safe adapter selection',
      'framework-neutral Runtime handle identity, permissions, and readiness',
      'framework-neutral adapter activation ordering and rollback',
      'framework-neutral cached Runtime projection reads and path validation',
      'framework-neutral latest-read Runtime query subscriptions and snapshots',
      'one-writer latest-intent Runtime selection',
      'framework-neutral committed-height RuntimeView catch-up',
      'framework-neutral injected RuntimeView loading and outcomes',
      'framework-neutral RuntimeView query, pagination, and height model',
      'framework-neutral selection-scoped detached RuntimeView projection reads',
      'framework-neutral latest-wins RuntimeView publication coordination',
      'framework-neutral RuntimeView refresh leases and invalidation',
      'framework-neutral RuntimeView selection snapshots and revisions',
      'framework-neutral RuntimeView snapshot and height transitions',
      'explicit remote attachment consent',
      'reconnect and failure states',
      'React-owned Runtime and authority overview shell',
      'React-owned Brain Vault and mnemonic identity entry with secret-free review',
      'React-owned mnemonic recovery rehearsal with public-address-only matching',
      'React-owned browser preferences for auth appearance and BrainVault worker caps',
      'React-owned redacted Runtime, browser-capability, and deploy-version diagnostics',
      'React-owned height-pinned financial-health reads with bounded retry and teardown',
      'React wallet WP6 requirement audit with explicit cross-work-package deferrals',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-recovery',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/apps/wallet/src/identity/identity-recovery.tsx',
      'frontend/apps/wallet/src/onboarding/wallet-identity-opening.ts',
      'frontend/apps/wallet/src/runtime/wallet-embedded-runtime.ts',
      'frontend/apps/wallet/src/recovery/wallet-recovery-services.tsx',
      'frontend/apps/wallet/src/recovery/wallet-recovery-services-source.ts',
      'frontend/apps/wallet/src/push-wake/wallet-push-wake.tsx',
      'frontend/apps/wallet/src/push-wake/wallet-push-wake-source.ts',
      'frontend/bridges/wallet/wallet-canonical-vault-runtime.ts',
      'frontend/bridges/wallet/wallet-canonical-recovery-services.ts',
      'frontend/bridges/wallet/wallet-canonical-push-wake.ts',
      'frontend/packages/browser/src/recovery/wallet-recovery-services.ts',
      'frontend/packages/browser/src/recovery/wallet-recovery-selection-session.ts',
      'frontend/packages/browser/src/wallet/wallet-push-wake.ts',
      'frontend/src/lib/utils/recovery',
    ],
    behavior: ['canonical encrypted backup-file import and restore', 'canonical recovery-service onboarding', 'push wake'],
    status: 'implemented',
  },
  {
    id: 'wallet-finance',
    owner: 'wallet',
    routes: ['/app', '/address'],
    currentSources: [
      'frontend/src/lib/components/Entity',
      'frontend/apps/wallet/src/portfolio/wallet-portfolio.tsx',
      'frontend/packages/runtime-client/src/account-workspace-tabs.ts',
      'frontend/packages/runtime-client/src/payments/withdrawable-collateral.ts',
      'frontend/apps/wallet/src/entity/wallet-entity-evidence.tsx',
      'frontend/apps/wallet/src/portfolio/wallet-portfolio-model.ts',
      'frontend/apps/wallet/src/portfolio/wallet-portfolio-source.ts',
      'frontend/apps/wallet/src/financial-health/wallet-financial-health.tsx',
      'frontend/apps/wallet/src/financial-health/wallet-financial-health-model.ts',
      'frontend/apps/wallet/src/financial-health/wallet-financial-health-solvency.ts',
      'frontend/apps/wallet/src/address/wallet-address-model.ts',
      'frontend/apps/wallet/src/address/wallet-address-source.ts',
      'frontend/apps/wallet/src/address/wallet-address.tsx',
    ],
    behavior: [
      'assets and accounts',
      'credit and collateral',
      'debt, solvency, and disputes',
      'React-owned committed RuntimeView assets and Account capacity projection',
      'React-owned debt, Runtime solvency evidence, Account dispute gates, and committed history',
      'React-owned address detail and bounded committed activity projection',
    ],
    status: 'in_progress',
  },
  {
    id: 'wallet-payments-and-markets',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/src/lib/components/Entity/swap',
      'frontend/packages/runtime-client/src/payments/payment-command.ts',
      'frontend/packages/runtime-client/src/payments/payment-command-types.ts',
      'frontend/packages/runtime-client/src/payments/xln-invoice.ts',
      'frontend/packages/browser/src/commands/runtime-command-intent.ts',
      'frontend/packages/browser/src/commands/runtime-command-intent-codec.ts',
      'frontend/packages/browser/src/commands/runtime-command-journal-indexed-db.ts',
      'frontend/packages/browser/src/commands/runtime-command-journal-keyring.ts',
      'frontend/packages/browser/src/commands/runtime-command-journal-storage.ts',
      'frontend/packages/browser/src/wallet/wallet-external-provider.ts',
      'frontend/apps/wallet/src/payments/wallet-payments.tsx',
      'frontend/apps/wallet/src/payments/wallet-payment-external.tsx',
      'frontend/apps/wallet/src/onboarding/wallet-external-provider-source.ts',
      'frontend/bridges/wallet/wallet-canonical-external-provider.ts',
      'frontend/apps/wallet/src/payments/wallet-payment-source.ts',
      'frontend/apps/wallet/src/payments/commands/wallet-payment-operations-model.ts',
      'frontend/apps/wallet/src/markets/wallet-markets.tsx',
      'frontend/apps/wallet/src/markets/wallet-market-source.ts',
      'frontend/apps/wallet/src/markets/wallet-market-model.ts',
      'frontend/apps/wallet/src/markets/wallet-market-command.ts',
    ],
    behavior: [
      'pay and receive',
      'invoices and moves',
      'orders, routing, and settlement',
      'React-owned Runtime route quotes and idempotent payment command retry',
      'React-owned canonical invoices and bounded reserve, collateral, settlement, and lending operations',
      'React-owned external wallet reads, signed transfers, exact approvals, reserve deposits, and withdrawals',
      'React-owned Runtime orderbooks, canonical same-j order and cancel commands, cross-j lifecycle, and persisted activity',
    ],
    status: 'implemented',
  },
  {
    id: 'wallet-native-and-offline',
    owner: 'wallet',
    routes: ['/app'],
    currentSources: [
      'frontend/src/lib/native',
      'frontend/src/lib/native/external-wallet-authority.ts',
      'frontend/packages/browser/src/wallet/wallet-external-provider.ts',
      'frontend/bridges/wallet/wallet-canonical-external-provider.ts',
      'frontend/capacitor.config.ts',
      'frontend/config/generated-inputs.ts',
      'frontend/apps/wallet/index.html',
      'frontend/static/site.webmanifest',
      'frontend/static/push-wake-sw.js',
      'frontend/static/route-mode.js',
      'frontend/scripts/pwa/pwa-candidate.ts',
      'frontend/scripts/pwa/pwa-candidate-smoke-server.ts',
      'scripts/native/stage-wallet-candidate.ts',
      'scripts/native/copy-capacitor-shell-candidate.ts',
      'scripts/native/copy-packaged-shell-candidate.ts',
      'scripts/native/packaged-shell-candidate-manifest.ts',
      'frontend/scripts/deployment/deployment-candidate.ts',
      'frontend/scripts/deployment/deployment-candidate-smoke-server.ts',
    ],
    behavior: [
      'deep links',
      'PWA and offline lifecycle',
      'mobile, desktop, and extension packaging',
      'isolated atomic candidate selection and whole-release rollback',
      'deterministic PWA and push-wake assets',
      'platform-resolved external wallet authority without signer material in React',
    ],
    status: 'implemented',
  },
  {
    id: 'ops-health-and-qa',
    owner: 'ops',
    routes: ['/health', '/qa', '/qa/hlt', '/qa/quorum'],
    currentSources: [
      'frontend/packages/runtime-client/src/admin-health.ts',
      'frontend/packages/runtime-client/src/runtime/rpc-health.ts',
      'frontend/packages/runtime-client/src/qa/evidence/qa-admin-evidence.ts',
      'frontend/packages/runtime-client/src/qa/evidence/qa-boundary.ts',
      'frontend/packages/runtime-client/src/qa/evidence/qa-cockpit-helpers.ts',
      'frontend/packages/runtime-client/src/qa/qa-hlt.ts',
      'frontend/packages/runtime-client/src/qa/quorum/qa-quorum-history.ts',
      'frontend/packages/runtime-client/src/qa/quorum/qa-quorum-model.ts',
      'frontend/packages/runtime-client/src/qa/quorum/qa-quorum-registry.ts',
      'frontend/packages/runtime-client/src/qa/quorum/qa-quorum-types.ts',
      'frontend/packages/runtime-client/src/qa/evidence/qa-performance-trend.ts',
      'frontend/packages/runtime-client/src/qa/qa-scenario-player.ts',
      'frontend/packages/runtime-client/src/qa/evidence/qa-test-ledger.ts',
      'frontend/packages/runtime-client/src/qa/evidence/qa-types.ts',
      'frontend/packages/browser/src/qa-api-client.ts',
      'frontend/src/routes/health/+page.svelte',
      'frontend/src/routes/qa/+page.svelte',
      'frontend/src/routes/qa/hlt/+page.svelte',
      'frontend/src/routes/qa/quorum/+page.svelte',
      'frontend/apps/ops/src/health/ops-health-model.ts',
      'frontend/apps/ops/src/health/ops-health-source.ts',
      'frontend/apps/ops/src/health/ops-health-runtime.ts',
      'frontend/apps/ops/src/health/ops-health.tsx',
      'frontend/apps/ops/src/hlt/ops-hlt-model.ts',
      'frontend/apps/ops/src/hlt/ops-hlt-source.ts',
      'frontend/apps/ops/src/hlt/ops-hlt-runtime.ts',
      'frontend/apps/ops/src/hlt/ops-hlt-controls.tsx',
      'frontend/apps/ops/src/hlt/ops-hlt-progress.tsx',
      'frontend/apps/ops/src/hlt/ops-hlt.tsx',
      'frontend/apps/ops/src/qa/ops-qa-model.ts',
      'frontend/apps/ops/src/qa/ops-qa-source.ts',
      'frontend/apps/ops/src/qa/ops-qa-actions.ts',
      'frontend/apps/ops/src/qa/ops-qa-runtime.ts',
      'frontend/apps/ops/src/qa/ops-qa.tsx',
      'frontend/apps/ops/src/quorum/ops-quorum-source.ts',
      'frontend/apps/ops/src/quorum/ops-quorum-chart.tsx',
      'frontend/apps/ops/src/quorum/ops-quorum-evidence.tsx',
      'frontend/apps/ops/src/quorum/ops-quorum.tsx',
    ],
    behavior: [
      'health state',
      'QA evidence',
      'HLT controls and results',
      'React-owned live health and RPC readiness with bounded retry, refresh, stale evidence, and teardown',
      'React-owned canonical HLT preview, record/replay/abort controls, active-run polling, and authoritative progress evidence',
      'React-owned QA run ledger, verdict, protected artifacts, restart authority, history maintenance, and page teardown',
      'React-owned strict audit-registry projection, model usefulness timeline, evidence detail, leaderboard, and explicit review chains',
    ],
    status: 'implemented',
  },
  {
    id: 'ops-runs-scenarios-and-ai',
    owner: 'ops',
    routes: ['/runs', '/scenarios', '/ai'],
    currentSources: [
      'frontend/src/routes/runs/+page.svelte',
      'frontend/src/routes/scenarios/+page.svelte',
      'frontend/src/routes/ai/[[chatId]]/+page.svelte',
      'frontend/packages/browser/src/runtime/session/runtime-scenario-source.ts',
      'frontend/packages/runtime-client/src/scenario/scenario-player-model.ts',
      'frontend/packages/runtime-client/src/scenario/scenario-runtime.ts',
      'frontend/packages/ui/src/stable-compare.ts',
      'frontend/apps/ops/src/runs/ops-runs.tsx',
      'frontend/apps/ops/src/runs/ops-runs-source.ts',
      'frontend/apps/ops/src/scenarios/ops-scenarios.tsx',
      'frontend/apps/ops/src/scenarios/ops-scenarios-runtime.ts',
      'frontend/apps/ops/src/ai/ops-ai.tsx',
      'frontend/apps/ops/src/ai/ops-ai-decode.ts',
      'frontend/apps/ops/src/ai/ops-ai-model.ts',
      'frontend/apps/ops/src/ai/ops-ai-source.ts',
      'frontend/apps/ops/src/ai/ops-ai-runtime.ts',
      'frontend/apps/ops/src/ai/ops-ai-header.tsx',
      'frontend/apps/ops/src/ai/ops-ai-messages.tsx',
      'frontend/apps/ops/src/ai/ops-ai-sidebar.tsx',
      'frontend/apps/wallet/src/scenario-preview/wallet-scenario-preview.tsx',
    ],
    behavior: [
      'run inspection',
      'scenario execution',
      'AI sessions and embed mode',
      'React-owned filterable run authority ledger with explicit failure evidence',
      'React-owned deterministic BrowserVM scenario execution, committed-frame playback, and teardown',
      'cross-application wallet preview reconstructed from scenario identity and frame index',
      'React-owned local AI console: chat, council deliberation, agent tools, voice wake word, camera vision, and MLX model control',
    ],
    status: 'in_progress',
  },
  {
    id: 'ops-workspace',
    owner: 'ops',
    routes: ['/embed'],
    currentSources: [
      'frontend/src/lib/view/View.svelte',
      'frontend/src/routes/embed/+page.svelte',
      'frontend/packages/runtime-client/src/panels/console-panel-view.ts',
      'frontend/packages/runtime-client/src/runtime/runtime-io-panel-view.ts',
      'frontend/packages/runtime-client/src/panels/solvency-panel-view.ts',
      'frontend/packages/runtime-client/src/runtime/runtime-diagnostics-panel-view.ts',
      'frontend/packages/runtime-client/src/panels/gossip-panel-view.ts',
      'frontend/packages/runtime-client/src/scenario/time-machine-transport.ts',
      'frontend/packages/runtime-client/src/panels/jurisdiction-panel-view.ts',
      'frontend/packages/runtime-client/src/panels/settings-panel-view.ts',
      'frontend/packages/runtime-client/src/panels/architect-panel-view.ts',
      'frontend/packages/runtime-client/src/graph/graph3d-entity-panel-view.ts',
      'frontend/packages/runtime-client/src/graph/graph3d-viewport-view.ts',
      'frontend/packages/runtime-client/src/graph/graph3d-scene-input.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-navigation.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-context.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-activity.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-consensus-evidence.ts',
      'frontend/packages/runtime-client/src/entity/profile/entity-workspace-hub-policy.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-accounts.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-ownership.ts',
      'frontend/packages/runtime-client/src/entity/profile/entity-workspace-profile.ts',
      'frontend/packages/runtime-client/src/entity/profile/entity-workspace-profile-update.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-reserves.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-settings-summary.ts',
      'frontend/packages/runtime-client/src/entity/entity-workspace-time-machine.ts',
      'frontend/packages/browser/src/display-preferences.ts',
      'frontend/packages/browser/src/theme-document.ts',
      'frontend/packages/runtime-client/src/workspace-dock-layout.ts',
      'frontend/packages/ui/src/workspace/workspace-dock.tsx',
      'frontend/packages/ui/src/theme-model.ts',
      'frontend/packages/ui/src/entity/settings/entity-workspace-display.ts',
      'frontend/packages/ui/src/entity/settings/entity-workspace-display-panel.tsx',
      'frontend/packages/ui/src/entity/settings/entity-workspace-display-panel.css',
      'frontend/packages/ui/src/entity/settings/entity-workspace-settings-stage.tsx',
      'frontend/packages/ui/src/entity/settings/entity-workspace-settings-stage.css',
      'frontend/packages/ui/src/entity/entity-workspace-time-machine.tsx',
      'frontend/packages/ui/src/entity/entity-workspace-time-machine.css',
      'frontend/packages/ui/src/entity/activity/entity-workspace-activity-panel.tsx',
      'frontend/packages/ui/src/entity/activity/entity-workspace-activity-row.tsx',
      'frontend/packages/ui/src/entity/activity/entity-workspace-activity-tone.ts',
      'frontend/packages/ui/src/entity/activity/entity-workspace-activity-panel.css',
      'frontend/packages/ui/src/entity/accounts/entity-workspace-consensus-panel.tsx',
      'frontend/packages/ui/src/entity/accounts/entity-workspace-consensus-panel.css',
      'frontend/packages/ui/src/entity/accounts/entity-workspace-accounts-panel.tsx',
      'frontend/packages/ui/src/entity/accounts/entity-workspace-accounts-panel.css',
      'frontend/packages/ui/src/entity/profile/entity-workspace-profile-panel.tsx',
      'frontend/packages/ui/src/entity/profile/entity-workspace-profile-panel.css',
      'frontend/packages/ui/src/entity/profile/entity-workspace-profile-editor.tsx',
      'frontend/packages/ui/src/entity/profile/entity-workspace-profile-editor.css',
      'frontend/packages/ui/src/entity/accounts/entity-workspace-reserves-panel.tsx',
      'frontend/packages/ui/src/entity/accounts/entity-workspace-reserves-panel.css',
      'frontend/packages/ui/src/entity/entity-workspace-shell.tsx',
      'frontend/packages/ui/src/entity/entity-workspace-shell.css',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace.tsx',
      'frontend/apps/ops/src/ops-display-preferences.ts',
      'frontend/apps/ops/src/workspace/settings/ops-settings-panel.tsx',
      'frontend/apps/ops/src/workspace/settings/ops-settings-camera.tsx',
      'frontend/apps/ops/src/workspace/settings/ops-settings-presentation.tsx',
      'frontend/apps/ops/src/workspace/runtime/ops-runtime-policies.tsx',
      'frontend/packages/runtime-client/src/operator-policy-settings.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-activity-controller.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-history.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-history-controller.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-projection.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-profile-command.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-owner.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-source.ts',
      'frontend/apps/ops/src/entity-workspace/ops-entity-workspace-runtime.ts',
      'frontend/apps/ops/src/workspace/ops-command-palette.tsx',
      'frontend/packages/ui/src/workspace/command-palette-view.ts',
      'frontend/packages/ui/src/workspace/command-palette-suggestions.ts',
      'frontend/apps/wallet/src/commands/wallet-command-draft.ts',
      'frontend/apps/ops/src/workspace/ops-workspace.tsx',
      'frontend/apps/ops/src/workspace/session/ops-workspace-panels.ts',
      'frontend/apps/ops/src/workspace/ops-pinned-tab.tsx',
      'frontend/apps/ops/src/workspace/session/ops-workspace-session.ts',
      'frontend/apps/ops/src/workspace/entity/ops-recorded-entity.ts',
      'frontend/apps/ops/src/workspace/owner/ops-owner-unlock.tsx',
      'frontend/apps/ops/src/workspace/runtime/ops-runtime-manager.tsx',
      'frontend/apps/ops/src/workspace/runtime/ops-runtime-selection.ts',
      'frontend/apps/ops/src/workspace/entity/ops-entity-panel.tsx',
      'frontend/apps/ops/src/workspace/entity/ops-entity-audit-panel.tsx',
      'frontend/apps/ops/src/workspace/panels/ops-console-panel.tsx',
      'frontend/apps/ops/src/workspace/runtime/ops-runtime-io-panel.tsx',
      'frontend/apps/ops/src/workspace/jurisdiction/ops-jmachine-inspector.tsx',
      'frontend/apps/ops/src/workspace/jurisdiction/ops-jurisdiction-panel.tsx',
      'frontend/apps/ops/src/workspace/jurisdiction/ops-jurisdiction-balances.tsx',
      'frontend/apps/ops/src/workspace/jurisdiction/ops-jurisdiction-view.ts',
      'frontend/apps/ops/src/workspace/panels/ops-architect-panel.tsx',
      'frontend/apps/ops/src/workspace/panels/ops-brainvault-panel.tsx',
      'frontend/apps/ops/src/workspace/panels/ops-database-inspector.tsx',
      'frontend/apps/ops/src/workspace/graph/ops-graph-panel.tsx',
      'frontend/apps/ops/src/workspace/graph/ops-graph-scene.ts',
      'frontend/apps/ops/src/workspace/graph/ops-graph-world.ts',
      'frontend/apps/ops/src/workspace/graph/ops-graph-preferences.ts',
      'frontend/apps/ops/src/workspace/session/ops-workspace-playback.ts',
      'frontend/apps/ops/src/workspace/session/ops-workspace-timeline.tsx',
      'frontend/apps/ops/src/workspace/guide/ops-workspace-guide.tsx',
      'frontend/packages/ui/src/mascot-geometry.ts',
      'frontend/apps/ops/src/workspace/guide/ops-guide-chat.tsx',
      'frontend/apps/ops/src/workspace/ops-locale-selector.tsx',
      'frontend/apps/ops/src/workspace/session/use-workspace-environment.ts',
      'frontend/bridges/runtime/browser-runtime-context.ts',
      'frontend/bridges/runtime/browser-runtime-session.ts',
      'frontend/bridges/ops-canonical-owner.ts',
      'frontend/bridges/workspace-localization.ts',
      'frontend/bridges/workspace-localization-react.ts',
      'frontend/apps/ops/src/workspace/ops-panel-title.ts',
      'frontend/packages/browser/src/indexed-db-inspector.ts',
      'frontend/packages/runtime-client/src/storage/indexed-db-inspector-key.ts',
      'frontend/packages/runtime-client/src/storage/indexed-db-inspector-object.ts',
      'frontend/packages/runtime-client/src/storage/indexed-db-inspector-value.ts',
      'frontend/apps/ops/src/workspace/panels/ops-wallet-panel.tsx',
      'frontend/packages/runtime-client/src/scenario/scenario-solvency.ts',
      'frontend/packages/ui/src/graph/graph3d-lifecycle.ts',
      'frontend/packages/ui/src/graph/graph3d-renderer.ts',
      'frontend/packages/ui/src/graph/graph3d-scene-primitives.ts',
      'frontend/packages/ui/src/graph/graph3d-visual-effects.ts',
      'frontend/packages/ui/src/graph/graph3d-entity-visuals.ts',
    ],
    behavior: [
      'Dockview layout',
      'Graph3D and Architect',
      'Runtime I/O, console, Solvency, Runtime Diagnostics, Gossip, and Time Machine',
      'framework-neutral panel projections shared with the canonical Svelte workspace',
      'framework-neutral Graph3D entity mini-panel projection with time-travel-aware Map/Record normalization',
      'framework-neutral Graph3D projection status, timeline, FPS, bars-mode, and VR HUD presentation state',
      'framework-neutral Graph3D runtime/jurisdiction scene inputs and recursive transaction normalization',
      'framework-neutral Entity workspace deep-link state, top-level and Settings section registries, strict identity/context, committed reserve, committed-board, bounded consensus-evidence, paged Account frame-header, filtered persisted activity, public profile, shared theme, and exact Time Machine state projections',
      'React candidate-only identity-first Entity shell with canonical hash-backed tabs, a tab-confined remote Runtime boundary, read-only Assets, Ownership, Accounts, filtered and paged persisted activity and Consensus evidence, authenticated owner-lane profile updates observed at the committed frame, shared-storage Display controls, and exact historical-frame navigation',
      'shared Svelte-compatible layout persistence and a lifecycle-safe React Dockview adapter',
      'framework-neutral Graph3D canvas, controls, resize, debug, renderer, and XR teardown boundaries',
      'shared Three.js renderer selection plus explicit geometry, material, and texture disposal',
      'shared Graph3D grid, Jurisdiction mesh, broadcast animation, and deterministic radial layout primitives',
      'shared directional-lightning and transaction-ripple visual effects',
      'shared Graph3D entity labels, mempool indicators, and node construction',
      'public fourteen-panel default workspace with sixteen retained component types, full-layout persistence and focus controls; internal host keeps canonical layout storage untouched',
      'docked Wallet reuses canonical React portfolio/payment/market/Account tools on the shared adapter, confines navigation to the panel, and unmounts commands for recorded frames',
      'visible local/remote vault-backed owner unlock, local durable restore/lock/reopen and expiry-aware profile commands; Runtime Manager attach/bulk/retry and shared session selection',
      'React Console, Runtime I/O, Entity Audit, J-Machine and readonly database inspection using retained data models',
      'React Graph3D with local/scenario full-state projection, Jurisdiction/grid layers, persisted camera and controls, Entity drag/open gestures, Account bars, and shared scenario/trail playback',
      'internal Settings policy forms, scene/camera/entity controls, Console, and presentation import/density with actual camera/focus cues; full Settings integration remains open',
      'retained guide geometry and local AI error handling plus ten-locale selection; complete labels and public embed host remain in progress',
    ],
    status: 'in_progress',
  },
] as const satisfies readonly CapabilityDefinition[];
