import { openWorkspaceStorageOrigin } from '../../browser-evidence';
import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from '../../browser-evidence';
import { installImportedRuntime, readWalletRuntimeFixture } from '../../wallet/fixtures/wallet-runtime-test-helpers';

test('recorded Gossip and Entity panels follow scenario selection without a live Runtime', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  const range = timeline.getByLabel('Network frame', { exact: true });
  await range.press('End');
  await page.getByRole('button', { name: 'Open Gossip panel', exact: true }).click();
  const gossip = page.getByTestId('runtime-gossip-panel');
  await expect(gossip).toContainText('4 profiles');
  await expect(gossip).toContainText('Recorded Runtime');
  await gossip.getByRole('button', { name: /^Open Entity / }).first().click();
  const entity = page.locator('.workspace-entity-pane[data-entity-id]');
  await expect(entity.getByTestId('entity-workspace-shell')).toHaveAttribute('data-read-status', 'ready');
  await expect(entity.getByTestId('entity-workspace-shell')).toHaveAttribute('data-runtime-id', 'scenario:ahb');
  await entity.getByTestId('entity-workspace-tab-settings').click();
  await entity.getByRole('link', { name: 'Display', exact: true }).click();
  await entity.getByRole('checkbox', { name: /Time Machine/i }).check();
  await expect(entity.getByTestId('entity-workspace-time-machine')).toHaveAttribute('data-mode', 'history');
  await entity.getByTestId('entity-workspace-tab-accounts').click();
  await screenshotEvidence(page, testInfo, 'ops-recorded-entity-activity');
  await range.press('Home');
  await expect(entity.getByTestId('entity-workspace-time-machine')).toHaveAttribute('data-mode', 'history');
  await range.press('End');
  await expect(entity.getByTestId('entity-workspace-shell')).toHaveAttribute('data-read-status', 'ready');
  await page.getByRole('button', { name: 'Open Entity Audit panel', exact: true }).click();
  const audit = page.getByTestId('entity-audit-panel');
  await expect(audit.locator('.ops-audit-status').first()).toContainText('scenario:ahb');
  await expect(audit.getByTestId('entity-audit-activity')).not.toHaveText('');
  await audit.getByRole('button', { name: 'Refresh', exact: true }).click();
  await screenshotEvidence(page, testInfo, 'ops-recorded-entity-audit');
  await page.getByRole('button', { name: 'Open Solvency panel', exact: true }).click();
  const solvency = page.getByTestId('solvency-panel');
  await expect(solvency.getByTestId('solvency-status')).toHaveText('?ASSET CONSERVATION NOT VERIFIED');
  await expect(solvency.getByTestId('solvency-asset').first()).toBeVisible();
  await expect(solvency).toContainText('recorded h126');
  await screenshotEvidence(page, testInfo, 'ops-recorded-solvency');
  await page.getByRole('button', { name: 'Open Runtime Diagnostics panel', exact: true }).click();
  const diagnostics = page.getByTestId('runtime-diagnostics-panel');
  await expect(diagnostics.getByTestId('runtime-diagnostics-history')).toBeVisible();
  await expect(diagnostics.getByRole('button', { name: 'Verify chain', exact: true })).toBeDisabled();
  await expect(diagnostics.getByTestId('runtime-security-summary')).toHaveCount(0);
  await screenshotEvidence(page, testInfo, 'ops-recorded-diagnostics-boundary');
  expect(await page.evaluate(() => localStorage.getItem('xln-vaults'))).toBeNull();
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('scenario Console, Runtime I/O and J-Machine inspection follow the shared frame', { tag: '@functional' }, async ({ page, context }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  const consolePanel = page.getByTestId('workspace-console');
  const command = consolePanel.getByLabel('Console command');
  await command.fill('sta');
  await command.press('Tab');
  await expect(command).toHaveValue('state()');
  await command.press('Enter');
  await expect(consolePanel.getByRole('log')).toContainText('"entities": 4');
  await command.press('ArrowUp');
  await expect(command).toHaveValue('state()');
  await command.press('ArrowDown');
  await expect(command).toHaveValue('');
  await command.fill('noSuchCommand()');
  await command.press('Enter');
  await expect(consolePanel.getByRole('log')).toContainText('Unknown command: noSuchCommand()');
  await consolePanel.getByLabel('Console log level', { exact: true }).selectOption('error');
  await consolePanel.getByRole('button', { name: 'Copy', exact: true }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('Unknown command: noSuchCommand()');
  await screenshotEvidence(page, testInfo, 'ops-console-command');
  await consolePanel.getByRole('button', { name: 'Clear', exact: true }).click();
  await expect(consolePanel.getByRole('log')).toHaveText('');
  await page.getByRole('button', { name: 'Open Runtime I/O panel', exact: true }).click();
  const io = page.getByTestId('workspace-runtime-io');
  await expect(io).toContainText('4 E-replicas');
  await io.locator('details').filter({ has: page.locator('summary', { hasText: /accounts$/ }) }).first().locator('summary').click();
  await expect(io.getByText('Accounts (Bilateral)', { exact: true }).first()).toBeVisible();
  await io.getByRole('searchbox', { name: 'Search Runtime logs' }).fill('no-matching-log');
  await expect(io).toContainText(/No logs match filters|No logs in this frame/);
  await screenshotEvidence(page, testInfo, 'ops-runtime-io-frame');
  await page.getByRole('button', { name: 'Open J-Machine Inspector panel', exact: true }).click();
  const machine = page.getByTestId('jmachine-storage-inspector');
  await machine.getByText('Raw J-Machine state', { exact: true }).click();
  await expect(machine.locator('pre')).toContainText('contracts');
  await expect(machine.getByRole('button', { name: 'Read code', exact: true })).toBeDisabled();
  await expect(machine.getByTestId('jmachine-bytecode-history')).toHaveText('Bytecode reads require Live. Contract code is not included in this recorded frame.');
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-scenario-jmachine');
  expectNoBrowserErrors(errors);
});

test('local-only inspectors remain restricted remotely and Entity Audit shares the selected session', { tag: '@functional' }, async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  await page.goto('/__app/ops/entity-workspace');
  for (const name of ['Console', 'Runtime I/O', 'J-Machine Inspector']) {
    await page.getByRole('button', { name: `Open ${name} panel`, exact: true }).click();
    await expect(page.getByRole('status', { name: '' }).filter({ hasText: 'This panel requires a local Runtime.' })).toBeVisible();
  }
  await page.getByRole('button', { name: 'Open Entity Audit panel', exact: true }).click();
  const audit = page.getByTestId('entity-audit-panel');
  await expect(audit.locator('.ops-audit-status')).toContainText([fixture.runtimeId, 'accounts cursor:']);
  await expect(audit.getByTestId('entity-audit-activity')).not.toHaveText('');
  await audit.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(audit.getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled();
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-entity-audit');
  expectNoBrowserErrors(errors);
});


test('local panels share the explicitly selected browser Runtime across close and reopen', { tag: '@functional' }, async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  await openWorkspaceStorageOrigin(page);
  await page.evaluate(() => localStorage.setItem('xln-runtime-adapter-mode', 'embedded'));
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  const consolePanel = page.getByTestId('workspace-console');
  const command = consolePanel.getByLabel('Console command');
  await expect(command).toBeVisible({ timeout: 45_000 });
  await command.fill('state()');
  await command.press('Enter');
  await expect(consolePanel.getByRole('log')).toContainText('"height":');
  await page.getByRole('button', { name: 'Open Runtime I/O panel', exact: true }).click();
  const io = page.getByTestId('workspace-runtime-io');
  await expect(io).toContainText('E-replicas');
  await page.locator('.dv-default-tab').filter({ hasText: /^Runtime I\/O$/ }).locator('.dv-default-tab-action').click();
  await page.getByRole('button', { name: 'Open Runtime I/O panel', exact: true }).click();
  await expect(io).toContainText('E-replicas');
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-local-runtime-context');
  expectNoBrowserErrors(errors);
});
