import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from '../../browser-evidence';
import { readWalletRuntimeFixture } from '../../wallet/fixtures/wallet-runtime-test-helpers';
import { installOpsOwnerMetadata } from '../owner/ops-owner-test-helpers';

test('Jurisdiction preserves exact recorded observations across frame and Entity selection', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  const frame = timeline.getByLabel('Network frame', { exact: true });
  await frame.press('End');
  await page.getByRole('button', { name: 'Open Jurisdiction panel', exact: true }).click();
  const panel = page.getByTestId('workspace-jurisdiction');
  await expect(panel).toContainText('Recorded · Runtime h126');
  const observer = panel.getByLabel('Jurisdiction observing Entity');
  await expect(observer.locator('option')).toHaveCount(4);
  await observer.selectOption({ index: 1 });
  await expect(panel.getByRole('table', { name: 'Jurisdiction reserves', exact: true }).locator('tbody tr')).not.toHaveCount(0);
  const token = panel.getByLabel('Jurisdiction token', { exact: true });
  await token.selectOption('1');
  await expect(token.locator('option:checked')).toContainText('USDC · #1');
  const reserves = panel.getByRole('table', { name: 'Jurisdiction reserves', exact: true });
  await expect(reserves.locator('tbody tr')).toHaveCount(1);
  await expect(reserves.locator('tbody tr td').first()).toHaveText('#1');
  const amount = await reserves.locator('tbody tr td').nth(1).innerText();
  expect(BigInt(amount)).toBeGreaterThanOrEqual(0n);
  await screenshotEvidence(page, testInfo, 'ops-jurisdiction-balances');
  await panel.getByRole('heading', { name: 'Active disputes', exact: true }).scrollIntoViewIfNeeded();
  await expect(panel).toContainText('No active disputes observed by this Entity.');
  await screenshotEvidence(page, testInfo, 'ops-jurisdiction-debts-wallet');
  await panel.getByRole('button', { name: 'Overview', exact: true }).click();
  await expect(panel).toContainText('depository:');
  await expect(panel).toContainText('State root');
  await screenshotEvidence(page, testInfo, 'ops-jurisdiction-overview');
  await frame.press('Home');
  await expect(panel).toContainText('Recorded · Runtime h1');
  await frame.press('End');
  await panel.getByRole('button', { name: 'Balances', exact: true }).click();
  await expect(reserves.locator('tbody tr td').nth(1)).toHaveText(amount);
  await expect(panel.getByTestId('jurisdiction-chain-history')).toHaveText('Recorded frames never query or time-travel the live provider.');
  await expect(panel.getByRole('table', { name: 'Fresh external balances' })).toHaveCount(0);
  await expect(panel.getByRole('table', { name: 'Fresh on-chain debts' })).toHaveCount(0);
  expect(await page.evaluate(() => localStorage.getItem('xln-workspace-layout'))).toBeNull();
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('Jurisdiction reads registry labels and fresh external balances/debts from the exact live stack', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await page.addInitScript(({ towerUrl, apiUrl }: { towerUrl: string; apiUrl: string }) => {
    localStorage.setItem('xln-watchtower-urls', JSON.stringify([towerUrl]));
    (window as typeof window & { __XLN_WATCHTOWERS__?: string[] }).__XLN_WATCHTOWERS__ = [towerUrl];
    (window as typeof window & { __XLN_API_BASE_URL__?: string }).__XLN_API_BASE_URL__ = apiUrl;
  }, { towerUrl: fixture.recovery.towerUrl, apiUrl: new URL(fixture.wsUrl.replace('ws:', 'http:')).origin });
  await page.goto('/scenarios/catalog.json');
  await installOpsOwnerMetadata(page, { ...fixture, entityId: fixture.recovery.entityId });
  await page.evaluate(() => localStorage.setItem('xln-runtime-adapter-mode', 'embedded'));
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Owner locked', exact: true }).click();
  const unlock = page.getByRole('form', { name: 'Unlock Runtime owner' });
  await unlock.getByLabel('Owner wallet seed phrase').fill(fixture.walletSeed);
  await unlock.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Owner unlocked', exact: true })).toBeVisible({ timeout: 60_000 });
  await page.getByRole('button', { name: 'Open Jurisdiction panel', exact: true }).click();
  const panel = page.getByTestId('workspace-jurisdiction');
  await expect(panel.getByLabel('Jurisdiction', { exact: true })).toHaveValue('React Recovery mnemonic');
  const token = panel.getByLabel('Jurisdiction token', { exact: true });
  await expect(token.locator('option:checked')).toHaveText('USDC · #1', { timeout: 30_000 });
  const balances = panel.getByRole('table', { name: 'Fresh external balances' });
  await expect(balances.locator('tbody tr')).toHaveCount(1, { timeout: 30_000 });
  await expect(balances).toContainText(fixture.recovery.external.initialBalance);
  await expect(balances).toContainText(fixture.recovery.runtimeId);
  const debts = panel.getByRole('table', { name: 'Fresh on-chain debts' });
  await expect(debts.locator('tbody tr')).toHaveCount(0);
  await expect(panel).toContainText('No outstanding debts returned by the selected stack.');
  await panel.getByRole('button', { name: 'Refresh chain reads', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Refresh chain reads', exact: true })).toBeEnabled();
  await expect(balances).toContainText(fixture.recovery.external.initialBalance);
  await screenshotEvidence(page, testInfo, 'ops-jurisdiction-live-chain');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});


test('Graph Jurisdiction pointer and keyboard navigation retain the selected panel', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  const graph = page.getByTestId('workspace-graph');
  await graph.getByLabel('Graph Jurisdiction', { exact: true }).selectOption('AHB Demo');
  const panel = page.getByTestId('workspace-jurisdiction');
  await expect(panel.getByLabel('Jurisdiction', { exact: true })).toHaveValue('AHB Demo');
  await panel.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await settings.getByRole('button', { name: 'Camera', exact: true }).click();
  await settings.getByLabel('Camera target y', { exact: true }).fill('600');
  await settings.getByLabel('Camera distance', { exact: true }).press('Home');
  for (let i = 0; i < 10; i++) await settings.getByLabel('Camera distance', { exact: true }).press('ArrowRight');
  await page.getByRole('button', { name: 'Open Graph3D panel', exact: true }).click();
  await expect(graph.locator('canvas')).toHaveAttribute('aria-busy', 'false');
  await graph.locator('canvas').scrollIntoViewIfNeeded();
  const box = await graph.locator('canvas').boundingBox();
  if (!box) throw new Error('GRAPH_CANVAS_BOUNDS_REQUIRED');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await expect(graph.getByRole('tooltip')).toHaveAttribute('data-kind', 'jurisdiction');
  await screenshotEvidence(page, testInfo, 'ops-graph-jurisdiction-hover');
  await graph.locator('canvas').click({ position: { x: box.width / 2, y: box.height / 2 } });
  await expect(panel.getByText('State root', { exact: true })).toBeVisible();
  await expect(page.locator('.dv-tab').filter({ hasText: /^AHB Demo$/ })).toHaveCount(1);
  await screenshotEvidence(page, testInfo, 'ops-graph-jurisdiction-retained');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});
