import { openWorkspaceStorageOrigin } from '../../browser-evidence';
import { expect, test, type WebSocket } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from '../../browser-evidence';
import { installImportedRuntime, readWalletRuntimeFixture } from '../../wallet/fixtures/wallet-runtime-test-helpers';

test('Architect records into shared playback and returns to the unchanged connected Wallet', async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  const sockets: WebSocket[] = [];
  page.on('websocket', socket => { if (socket.url() === fixture.wsUrl) sockets.push(socket); });
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Wallet panel', exact: true }).click();
  const wallet = page.getByTestId('ops-wallet-panel');
  await wallet.getByLabel('Entity', { exact: true }).selectOption(fixture.entityId);
  const assets = wallet.getByRole('table', { name: 'Committed asset positions' });
  await expect(assets).toContainText('USDC');
  const before = await assets.innerText();
  await page.getByRole('button', { name: 'Open Architect panel', exact: true }).click();
  const architect = page.getByTestId('workspace-architect');
  await expect(architect.getByLabel('Architect scenario').locator('option')).toHaveCount(9);
  await architect.getByLabel('Architect scenario').selectOption('ahb');
  await architect.getByRole('button', { name: 'Run scenario', exact: true }).click();
  await expect(architect.getByRole('status')).toHaveText('ahb: 126 recorded network steps', { timeout: 90_000 });
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/126');
  await expect(wallet).toHaveCount(0);
  await expect(architect.getByLabel('AHB scenario source')).toHaveValue(/async function ahb/);
  await screenshotEvidence(page, testInfo, 'ops-architect-recorded');
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  await architect.getByText('Selected frame', { exact: true }).click();
  await expect(architect.locator('pre')).toContainText('"height": 126');
  await architect.getByRole('button', { name: 'Solvency', exact: true }).click();
  await expect(architect.getByTestId('solvency-panel')).toContainText('recorded h126');
  await expect(architect.getByTestId('solvency-asset').first()).toBeVisible();
  await screenshotEvidence(page, testInfo, 'ops-architect-solvency');
  await page.getByRole('button', { name: 'Open Gossip panel', exact: true }).click();
  await expect(page.getByTestId('runtime-gossip-panel')).toContainText('4 profiles');
  await page.getByRole('button', { name: 'Open Architect panel', exact: true }).click();
  await expect(architect.getByTestId('solvency-panel')).toBeVisible();
  await architect.getByRole('button', { name: 'Scenarios', exact: true }).click();
  await architect.getByRole('button', { name: 'Live Runtime', exact: true }).click();
  await page.getByRole('button', { name: 'Open Wallet panel', exact: true }).click();
  await expect(wallet).toHaveAttribute('data-runtime-id', fixture.runtimeId);
  await wallet.getByLabel('Entity', { exact: true }).selectOption(fixture.entityId);
  await expect.poll(() => assets.innerText()).toBe(before);
  expect(sockets).toHaveLength(1);
  expect(sockets[0]?.isClosed()).toBe(false);
  expect(await page.evaluate(() => localStorage.getItem('xln-workspace-layout'))).toBeNull();
  await screenshotEvidence(page, testInfo, 'ops-architect-restored-wallet');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});
