import { expect, test, type Page, type WebSocket } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, openWorkspaceStorageOrigin, screenshotEvidence } from './browser-evidence';
import { installImportedRuntime, readWalletRuntimeFixture } from './wallet-runtime-test-helpers';
import { installOpsOwnerMetadata, unlockOpsOwnerVisibly } from './ops-owner-test-helpers';

const command = async (page: Page, text: string): Promise<void> => {
  await page.getByRole('button', { name: 'Open command palette', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Workspace commands' });
  await dialog.getByRole('combobox').fill(text);
  await expect(dialog.getByRole('option').first()).toBeVisible();
  await dialog.getByRole('combobox').press('Enter');
};

test('palette opens editable payment, swap and Account drafts in the retained selected Wallet', { tag: '@functional' }, async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  await installOpsOwnerMetadata(page, fixture);
  const sockets: WebSocket[] = [];
  page.on('websocket', socket => { if (socket.url() === fixture.wsUrl) sockets.push(socket); });
  await page.goto('/__app/ops/entity-workspace');
  await unlockOpsOwnerVisibly(page, fixture.walletSeed);
  await page.getByRole('button', { name: 'Open Wallet panel', exact: true }).click();
  const wallet = page.getByTestId('ops-wallet-panel');
  await wallet.getByLabel('Entity', { exact: true }).selectOption(fixture.entityId);
  await expect(wallet.getByRole('table', { name: 'Committed asset positions' })).toContainText('USDC');
  await command(page, `pay 2.5 usdc to ${fixture.counterpartyEntityId}`);
  await expect(page.getByRole('dialog', { name: 'Workspace commands' })).not.toBeVisible();
  await expect(wallet.getByLabel('Entity', { exact: true })).toHaveValue(fixture.entityId);
  await expect(wallet.getByRole('combobox', { name: 'Recipient', exact: true })).toHaveValue(fixture.counterpartyEntityId);
  const amount = wallet.getByLabel('Recipient amount', { exact: true });
  await expect(amount).toHaveValue('2.5');
  await expect(amount).toBeEditable();
  await amount.fill('3.5');
  await amount.press('Control+k');
  await expect(page.getByRole('dialog', { name: 'Workspace commands' })).not.toBeVisible();
  await page.getByRole('button', { name: 'Open Gossip panel', exact: true }).click();
  await page.getByRole('button', { name: 'Open Wallet panel', exact: true }).click();
  await expect(amount).toHaveValue('3.5');
  await amount.scrollIntoViewIfNeeded();
  await expect(amount).toBeInViewport();
  await screenshotEvidence(page, testInfo, 'ops-palette-payment-draft');
  await command(page, 'swap 0.5 weth for usdc');
  const give = wallet.locator('.wallet-order-ticket label').filter({ hasText: /^Give/ });
  await expect(give.locator('input')).toHaveValue('0.5');
  await expect(give.locator('select option:checked')).toHaveText('WETH');
  const receive = wallet.locator('.wallet-order-ticket label').filter({ hasText: /^Receive at least/ });
  await expect(receive.locator('select option:checked')).toHaveText('USDC');
  await expect(receive.locator('input')).toHaveValue('');
  await expect(wallet.getByRole('button', { name: 'Submit canonical order' })).toBeDisabled();
  await give.locator('input').fill('0.75');
  await wallet.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(wallet.getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled();
  await expect(give.locator('input')).toHaveValue('0.75');
  await command(page, 'swap 0.25 weth for usdc');
  await expect(give.locator('input')).toHaveValue('0.25');
  await expect(give.locator('input')).toBeInViewport();
  await screenshotEvidence(page, testInfo, 'ops-palette-swap-draft');
  await command(page, `open ${fixture.counterpartyEntityId}`);
  const direct = wallet.getByRole('form', { name: 'Open Account by ID' });
  await expect(direct.getByPlaceholder('Select or paste entity ID')).toHaveValue(fixture.counterpartyEntityId);
  await expect(direct.getByPlaceholder('Select or paste entity ID')).toBeInViewport();
  await screenshotEvidence(page, testInfo, 'ops-palette-account-draft');
  await command(page, `pay 1 unavailabletoken to ${fixture.counterpartyEntityId}`);
  await expect(wallet.getByRole('alert')).toHaveText('Wallet token UNAVAILABLETOKEN is unavailable in the selected Entity.');
  await expect(wallet.getByRole('button', { name: 'Find route' })).toHaveCount(0);
  await expect(wallet.getByRole('alert')).toBeInViewport();
  await screenshotEvidence(page, testInfo, 'ops-palette-unavailable-token');
  expect(sockets).toHaveLength(1);
  expect(sockets[0]?.isClosed()).toBe(false);
  await expect(page).toHaveURL(/\/__app\/ops\/entity-workspace$/);
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('public palette searches the recorded frame, preserves focus navigation, and rejects live drafts', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/embed?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/126', { timeout: 90_000 });
  const entityId = await page.getByLabel('Graph Entity', { exact: true }).locator('option').nth(1).getAttribute('value');
  if (!entityId) throw new Error('SCENARIO_ENTITY_REQUIRED');
  await page.locator('.ops-workspace-toolbar > strong').click();
  await page.keyboard.press('Control+k');
  const dialog = page.getByRole('dialog', { name: 'Workspace commands' });
  await expect(dialog).toBeVisible();
  await screenshotEvidence(page, testInfo, 'ops-palette-suggestions');
  await dialog.getByRole('combobox').fill('swap 1 usdc for weth');
  await dialog.getByRole('combobox').press('Enter');
  await expect(dialog.getByRole('alert')).toHaveText('Return to Live to open a Wallet draft.');
  await dialog.getByRole('combobox').fill(entityId);
  await dialog.getByRole('combobox').press('Enter');
  await expect(dialog).not.toBeVisible();
  await expect(page.locator(`.dv-active-group .workspace-entity-pane[data-entity-id="${entityId}"]`)).toBeVisible();
  await expect(page.getByRole('button', { name: 'Full layout', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await screenshotEvidence(page, testInfo, 'ops-palette-recorded-entity');
  await page.getByRole('button', { name: 'Open command palette', exact: true }).click();
  await dialog.getByRole('combobox').press('Escape');
  await expect(dialog).not.toBeVisible();
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});
