import { openWorkspaceStorageOrigin } from './browser-evidence';
import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from './browser-evidence';
import { installImportedRuntime, readWalletRuntimeFixture } from './wallet-runtime-test-helpers';
import { finishOpenedWalletSetup } from './wallet-onboarding-test-helpers';

test('docked BrainVault restores a canonical backup and hands the local Runtime to every panel', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(150_000);
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await page.addInitScript((towerUrl: string) => {
    localStorage.setItem('xln-watchtower-urls', JSON.stringify([towerUrl]));
    (window as typeof window & { __XLN_WATCHTOWERS__?: string[] }).__XLN_WATCHTOWERS__ = [towerUrl];
  }, fixture.recovery.towerUrl);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Wallet panel', exact: true }).click();
  const wallet = page.getByTestId('ops-wallet-panel');
  await expect(wallet.getByRole('heading', { name: 'Assets & accounts' })).toBeVisible();
  await page.getByRole('button', { name: 'Open BrainVault panel', exact: true }).click();
  const brainvault = page.getByTestId('workspace-brainvault');
  await expect(brainvault).toBeVisible();
  await expect(page).toHaveURL(/\/__app\/ops\/entity-workspace$/);
  await screenshotEvidence(page, testInfo, 'ops-brainvault-entry');
  const mnemonic = 'test test test test test test test test test test test junk';
  await brainvault.getByRole('tab', { name: /Mnemonic/ }).click();
  await brainvault.getByRole('textbox', { name: /^Seed phrase/ }).fill(mnemonic);
  await brainvault.getByRole('button', { name: 'Review identity inputs' }).click();
  await brainvault.getByRole('button', { name: 'Verify recovery' }).click();
  await brainvault.getByRole('textbox', { name: /^Seed phrase/ }).fill(mnemonic);
  await brainvault.getByRole('button', { name: 'Verify recovered wallet' }).click();
  await brainvault.getByRole('button', { name: 'Check recovery and open wallet' }).click();
  await expect(brainvault.getByRole('heading', { name: 'Choose a backup' })).toBeVisible({ timeout: 90_000 });
  await screenshotEvidence(page, testInfo, 'ops-brainvault-backup-choice');
  await brainvault.getByRole('button', { name: 'Restore selected backup' }).click();
  await expect(brainvault.getByRole('heading', { name: 'Wallet opened' })).toBeVisible({ timeout: 90_000 });
  await expect(page.getByTestId('ops-owner-unlock')).toHaveAttribute('data-runtime-status', 'ready');
  await page.getByRole('button', { name: 'Open Wallet panel', exact: true }).click();
  await expect(wallet.getByRole('heading', { name: 'Configure account' })).toBeVisible();
  await expect(wallet.getByRole('heading', { name: 'Assets & accounts' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Open BrainVault panel', exact: true }).click();
  await finishOpenedWalletSetup(page);
  await screenshotEvidence(page, testInfo, 'ops-brainvault-opened');
  await brainvault.getByRole('link', { name: 'Continue to assets' }).click();
  await expect(wallet).toHaveAttribute('data-runtime-id', fixture.recovery.runtimeId);
  await expect(wallet.getByRole('heading', { name: 'Assets & accounts' })).toBeVisible();
  await expect(page).toHaveURL(/\/__app\/ops\/entity-workspace$/);
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  const consolePanel = page.getByTestId('workspace-console');
  await consolePanel.getByLabel('Console command').fill('state()');
  await consolePanel.getByLabel('Console command').press('Enter');
  await expect(consolePanel.getByRole('log')).toContainText('"entities": 1');
  await screenshotEvidence(page, testInfo, 'ops-brainvault-shared-console');
  expect(await page.evaluate(() => localStorage.getItem('xln-workspace-layout'))).toBeNull();
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});
