import { openWorkspaceStorageOrigin } from './browser-evidence';
import { expect, test, type Locator, type WebSocket } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from './browser-evidence';
import { installImportedRuntime, readWalletRuntimeFixture } from './wallet-runtime-test-helpers';

const openTool = async (wallet: Locator, id: string): Promise<void> => {
  const mobile = wallet.getByTestId('account-workspace-mobile-toggle');
  if (await mobile.isVisible()) await mobile.click();
  await wallet.getByTestId(`account-workspace-tab-${id}`).filter({ visible: true }).click();
};

test('docked Wallet borrows one Runtime across Account, payment and market navigation', { tag: '@functional' }, async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  const sockets: WebSocket[] = [];
  page.on('websocket', socket => { if (socket.url() === fixture.wsUrl) sockets.push(socket); });
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Wallet panel' }).click();
  const wallet = page.getByTestId('ops-wallet-panel');
  await expect(wallet).toHaveAttribute('data-runtime-id', fixture.runtimeId);
  await expect(wallet.getByRole('heading', { name: 'Assets & accounts' })).toBeVisible();
  await wallet.getByLabel('Entity', { exact: true }).selectOption(fixture.entityId);
  await expect(wallet.getByRole('table', { name: 'Committed asset positions' })).toContainText('USDC');
  await screenshotEvidence(page, testInfo, 'ops-wallet-assets');
  await openTool(wallet, 'send');
  await expect(wallet.getByRole('heading', { name: 'Payments' })).toBeVisible();
  await expect(wallet.getByLabel('Entity', { exact: true })).toHaveValue(fixture.entityId);
  await wallet.getByLabel('Recipient amount').fill('1');
  await wallet.locator('.wallet-payment-modes label').filter({ hasText: 'Direct' }).click();
  await wallet.getByRole('button', { name: 'Find route' }).click();
  await expect(wallet.getByText('Cheapest eligible route')).toBeVisible();
  await wallet.getByRole('button', { name: 'Submit quoted payment' }).scrollIntoViewIfNeeded();
  await expect(wallet.getByRole('button', { name: 'Submit quoted payment' })).toBeInViewport();
  await expect(page.locator('.dv-tab').filter({ hasText: /^Wallet$/ })).toBeInViewport();
  expect(await wallet.evaluate(element => element.closest('.dv-view')?.scrollTop)).toBe(0);
  await screenshotEvidence(page, testInfo, 'ops-wallet-payment-quote');
  await openTool(wallet, 'swap');
  await expect(wallet.getByRole('heading', { name: 'Markets' })).toBeVisible();
  await expect(wallet.getByRole('region', { name: 'Market selection' })).toContainText('USDC / WETH');
  await screenshotEvidence(page, testInfo, 'ops-wallet-market');
  await wallet.getByRole('navigation', { name: 'Wallet sections' }).getByRole('button', { name: 'Assets', exact: true }).click();
  await wallet.getByRole('button', { name: 'View Account' }).first().click();
  await expect(wallet.getByTestId('account-panel')).toBeVisible();
  await wallet.getByRole('button', { name: 'Manage', exact: true }).click();
  await expect(wallet.getByRole('heading', { name: 'Manage Account' })).toBeVisible();
  await expect(wallet.getByLabel('Entity', { exact: true })).toHaveValue(fixture.entityId);
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-wallet-manage');
  await openTool(wallet, 'move');
  await expect(wallet.getByRole('heading', { name: 'Move', exact: true })).toBeVisible();
  await expect(wallet.getByLabel('Entity', { exact: true })).toHaveValue(fixture.entityId);
  await screenshotEvidence(page, testInfo, 'ops-wallet-move');
  await expect(page).toHaveURL(/\/__app\/ops\/entity-workspace$/);
  expect(sockets).toHaveLength(1);
  await page.locator('.dv-tab').filter({ hasText: /^Wallet$/ }).locator('.dv-default-tab-action').click();
  await expect(wallet).toHaveCount(0);
  await page.getByRole('button', { name: 'Open Gossip panel' }).click();
  await expect(page.getByTestId('runtime-gossip-panel')).toContainText('Browser Hub');
  expect(sockets[0]?.isClosed()).toBe(false);
  await page.getByRole('button', { name: 'Open Wallet panel' }).click();
  await expect(wallet.getByRole('table', { name: 'Committed asset positions' })).toBeVisible();
  expect(sockets).toHaveLength(1);
  const timeline = page.getByTestId('workspace-network-timeline');
  await timeline.getByRole('button', { name: 'Load timeline' }).click();
  await expect(timeline.getByRole('button', { name: 'Next network frame' })).toBeEnabled();
  await timeline.getByRole('button', { name: 'Next network frame' }).click();
  await expect(timeline.locator('output')).toContainText('/');
  await expect(wallet).toHaveCount(0);
  await timeline.getByRole('button', { name: 'Live', exact: true }).click();
  await expect(wallet.getByRole('table', { name: 'Committed asset positions' })).toBeVisible();
  expect(sockets).toHaveLength(1);
  expectNoBrowserErrors(errors);
});

test('docked Wallet follows the selected scenario without mounting live commands', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await timeline.getByLabel('Network frame', { exact: true }).focus();
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  await page.getByRole('button', { name: 'Open Wallet panel' }).click();
  const entity = page.getByTestId('entity-workspace-shell').filter({ visible: true });
  await expect(entity).toHaveAttribute('data-entity-id', /0x[0-9a-f]{64}/);
  await expect(page.getByTestId('ops-wallet-panel')).toHaveCount(0);
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-wallet-recorded');
  expectNoBrowserErrors(errors);
});
