import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from './browser-evidence';

test('Jurisdiction preserves exact recorded observations across frame and Entity selection', async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  const frame = timeline.getByLabel('Network frame', { exact: true });
  await frame.press('End');
  await page.getByRole('button', { name: 'Open Jurisdiction panel', exact: true }).click();
  const panel = page.getByTestId('workspace-jurisdiction');
  await expect(panel).toContainText('Recorded · Runtime h126');
  const observer = panel.getByLabel('Jurisdiction observing Entity');
  await expect(observer.locator('option')).toHaveCount(4);
  await observer.selectOption({ index: 1 });
  await expect(panel.getByRole('table', { name: 'Jurisdiction reserves', exact: true }).locator('tbody tr')).not.toHaveCount(0);
  const token = panel.getByLabel('Jurisdiction token', { exact: true });
  await token.selectOption('1');
  const reserves = panel.getByRole('table', { name: 'Jurisdiction reserves', exact: true });
  await expect(reserves.locator('tbody tr')).toHaveCount(1);
  await expect(reserves.locator('tbody tr td').first()).toHaveText('#1');
  const amount = await reserves.locator('tbody tr td').nth(1).innerText();
  expect(BigInt(amount)).toBeGreaterThanOrEqual(0n);
  await screenshotEvidence(page, testInfo, 'ops-jurisdiction-balances');
  await panel.getByRole('heading', { name: 'Active disputes', exact: true }).scrollIntoViewIfNeeded();
  await expect(panel).toContainText('No active disputes observed by this Entity.');
  await screenshotEvidence(page, testInfo, 'ops-jurisdiction-debts-wallet');
  await panel.getByRole('button', { name: 'Overview', exact: true }).click();
  await expect(panel).toContainText('depository:');
  await expect(panel).toContainText('State root');
  await screenshotEvidence(page, testInfo, 'ops-jurisdiction-overview');
  await frame.press('Home');
  await expect(panel).toContainText('Recorded · Runtime h1');
  await frame.press('End');
  await panel.getByRole('button', { name: 'Balances', exact: true }).click();
  await expect(reserves.locator('tbody tr td').nth(1)).toHaveText(amount);
  expect(await page.evaluate(() => localStorage.getItem('xln-workspace-layout'))).toBeNull();
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});


test('Graph Jurisdiction pointer and keyboard navigation retain the selected panel', async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  const graph = page.getByTestId('workspace-graph');
  await graph.getByLabel('Graph Jurisdiction', { exact: true }).selectOption('AHB Demo');
  const panel = page.getByTestId('workspace-jurisdiction');
  await expect(panel.getByLabel('Jurisdiction', { exact: true })).toHaveValue('AHB Demo');
  await panel.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await settings.getByRole('button', { name: 'Camera', exact: true }).click();
  await settings.getByLabel('Camera target y', { exact: true }).fill('600');
  await settings.getByLabel('Camera distance', { exact: true }).press('Home');
  for (let i = 0; i < 10; i++) await settings.getByLabel('Camera distance', { exact: true }).press('ArrowRight');
  await page.getByRole('button', { name: 'Open Graph3D panel', exact: true }).click();
  await expect(graph.locator('canvas')).toHaveAttribute('aria-busy', 'false');
  await graph.locator('canvas').scrollIntoViewIfNeeded();
  const box = await graph.locator('canvas').boundingBox();
  if (!box) throw new Error('GRAPH_CANVAS_BOUNDS_REQUIRED');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await expect(graph.getByRole('tooltip')).toHaveAttribute('data-kind', 'jurisdiction');
  await screenshotEvidence(page, testInfo, 'ops-graph-jurisdiction-hover');
  await graph.locator('canvas').click({ position: { x: box.width / 2, y: box.height / 2 } });
  await expect(panel.getByText('State root', { exact: true })).toBeVisible();
  await expect(page.locator('.dv-tab').filter({ hasText: /^AHB Demo$/ })).toHaveCount(1);
  await screenshotEvidence(page, testInfo, 'ops-graph-jurisdiction-retained');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});
