import { openWorkspaceStorageOrigin } from './browser-evidence';
import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from './browser-evidence';
import { readWalletRuntimeFixture } from './wallet-runtime-test-helpers';
import { installOpsOwnerMetadata } from './ops-owner-test-helpers';

test('local restoration failure keeps unlocked keys revocable without claiming a ready Runtime', async ({ page }, testInfo) => {
  testInfo.setTimeout(90_000);
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installOpsOwnerMetadata(page, { ...fixture, entityId: fixture.recovery.entityId });
  await page.evaluate(() => localStorage.setItem('xln-runtime-adapter-mode', 'embedded'));
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Owner locked', exact: true }).click();
  const form = page.getByRole('form', { name: 'Unlock Runtime owner' });
  await form.getByLabel('Owner wallet seed phrase').fill(fixture.walletSeed);
  await form.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(form.getByRole('button', { name: 'Working…', exact: true })).toHaveCount(0, { timeout: 45_000 });
  await expect(form.getByRole('alert')).toContainText('persisted env missing');
  await expect(page.getByRole('button', { name: 'Owner keys unlocked', exact: true })).toBeVisible();
  await expect(form).toContainText('commands remain unavailable');
  await expect(page.getByTestId('ops-owner-unlock')).toHaveAttribute('data-runtime-status', 'error');
  await screenshotEvidence(page, testInfo, 'ops-local-owner-restore-failed');
  await form.getByRole('button', { name: 'Lock owner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Owner locked', exact: true })).toBeVisible();
  await expect(form.getByRole('alert')).toHaveCount(0);
  await expect(form.getByLabel('Owner wallet seed phrase')).toHaveValue('');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('a locked local vault visibly unlocks through the shared Runtime session and relocks', async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await page.addInitScript(({ towerUrl, apiUrl }: { towerUrl: string; apiUrl: string }) => {
    localStorage.setItem('xln-watchtower-urls', JSON.stringify([towerUrl]));
    (window as typeof window & { __XLN_WATCHTOWERS__?: string[] }).__XLN_WATCHTOWERS__ = [towerUrl];
    (window as typeof window & { __XLN_API_BASE_URL__?: string }).__XLN_API_BASE_URL__ = apiUrl;
  }, { towerUrl: fixture.recovery.towerUrl, apiUrl: new URL(fixture.wsUrl.replace('ws:', 'http:')).origin });
  await openWorkspaceStorageOrigin(page);
  await installOpsOwnerMetadata(page, { ...fixture, entityId: fixture.recovery.entityId });
  await page.evaluate(() => localStorage.setItem('xln-runtime-adapter-mode', 'embedded'));
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Owner locked', exact: true }).click();
  const form = page.getByRole('form', { name: 'Unlock Runtime owner' });
  await expect(form).toContainText('Local Runtime owner');
  await form.getByLabel('Owner wallet seed phrase').fill('abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about');
  await form.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(form.getByRole('alert')).toHaveText('RUNTIME_UNLOCK_SEED_MISMATCH', { timeout: 45_000 });
  await form.getByLabel('Owner wallet seed phrase').fill(fixture.walletSeed);
  await form.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(form.getByRole('button', { name: 'Working…', exact: true })).toHaveCount(0, { timeout: 60_000 });
  await expect(form.getByRole('alert')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Owner unlocked', exact: true })).toBeVisible({ timeout: 60_000 });
  await expect(page.getByTestId('ops-owner-unlock')).toHaveAttribute('data-runtime-status', 'ready');
  if (await form.isVisible()) await page.getByRole('button', { name: 'Owner unlocked', exact: true }).click();
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  const consolePanel = page.getByTestId('workspace-console');
  const command = consolePanel.getByLabel('Console command');
  await command.fill('state()');
  await command.press('Enter');
  await expect(consolePanel.getByRole('log')).toContainText('"height":');
  const selected = await page.evaluate(async () => {
    const moduleUrl = '/__app/ops/src/ops-entity-workspace-runtime.ts';
    const module = await import(moduleUrl);
    const adapter = module.opsEntityWorkspaceSource.getAdapter();
    return { runtimeId: adapter.runtimeId, mode: adapter.mode };
  });
  expect(selected).toEqual({ runtimeId: fixture.runtimeId, mode: 'embedded' });
  const stored = await page.evaluate(() => localStorage.getItem('xln-vaults'));
  expect(stored).toContain('protectedSecrets');
  expect(stored).not.toContain(fixture.walletSeed);
  await page.getByRole('button', { name: 'Open Entity panel', exact: true }).click();
  await page.getByTestId('entity-workspace-tab-settings').click();
  await page.getByTestId('settings-profile-name-input').fill(`Local owner ${testInfo.project.name}`);
  await page.getByTestId('settings-profile-save').click();
  await expect(page.getByTestId('settings-profile-status')).toHaveText('Profile committed to the selected Entity.', { timeout: 30_000 });
  await screenshotEvidence(page, testInfo, 'ops-local-owner-unlocked');
  await page.getByRole('button', { name: 'Open Runtime Diagnostics panel', exact: true }).click();
  const diagnostics = page.getByTestId('runtime-diagnostics-panel');
  await expect(diagnostics.getByTestId('runtime-diagnostics-adapter')).toHaveText('browser');
  await expect(diagnostics.getByTestId('runtime-security-summary')).toHaveText('No active security incidents.');
  await diagnostics.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(diagnostics.getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled();
  await expect(diagnostics.getByTestId('runtime-security-summary')).toHaveText('No active security incidents.');
  await diagnostics.getByRole('button', { name: 'Verify chain', exact: true }).click();
  await expect(diagnostics.getByTestId('runtime-diagnostics-verification')).toContainText('"ok": true');
  await screenshotEvidence(page, testInfo, 'ops-local-runtime-diagnostics');
  await page.getByRole('button', { name: 'Open J-Machine Inspector panel', exact: true }).click();
  const machine = page.getByTestId('jmachine-storage-inspector');
  await machine.getByRole('button', { name: 'Read code', exact: true }).click();
  await expect(machine.locator('tbody tr')).toHaveCount(4);
  await expect(machine.getByRole('alert')).toHaveCount(0);
  for (const row of await machine.locator('tbody tr').all()) {
    await expect(row.locator('td').last()).toHaveText(/^[1-9][\d,]* \/ 24,576$/);
  }
  expect(await machine.locator('.ops-panel-table').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await screenshotEvidence(page, testInfo, 'ops-local-jmachine-bytecode');
  await page.getByRole('button', { name: 'Open Entity panel', exact: true }).click();
  await page.getByRole('button', { name: 'Owner unlocked', exact: true }).click();
  await form.getByRole('button', { name: 'Lock owner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Owner locked', exact: true })).toBeVisible();
  await expect(form.getByRole('button', { name: 'Unlock owner', exact: true })).toBeDisabled();
  await screenshotEvidence(page, testInfo, 'ops-local-owner-locked');
  await form.getByLabel('Owner wallet seed phrase').fill(fixture.walletSeed);
  await form.getByRole('button', { name: 'Unlock owner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Owner unlocked', exact: true })).toBeVisible({ timeout: 60_000 });
  await expect(page.getByTestId('settings-profile-name-input')).toHaveValue(`Local owner ${testInfo.project.name}`);
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  await expect(command).toBeVisible();
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});
