import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from './browser-evidence';
import { finishOpenedWalletSetup, restoreLocalWallet } from './wallet-onboarding-test-helpers';
import { selectWalletFixtureRuntime } from './wallet-runtime-test-helpers';

test('direct Account opening resolves recipients, rejects invalid targets and commits through the retained command', async ({ page }, testInfo) => {
  testInfo.setTimeout(150_000);
  const errors = observeBrowserErrors(page);
  const fixture = await restoreLocalWallet(page, 'hub-discovery');
  await finishOpenedWalletSetup(page);
  await page.getByRole('link', { name: 'Continue to assets' }).click();
  await page.getByLabel('Entity', { exact: true }).selectOption(fixture.recovery.entityId);
  const hubId = fixture.recovery.hubDiscovery.hubEntityId;
  await expect(page.locator('.account-rail-desktop a')).toHaveCount(1);
  await expect(page.locator('.account-rail-desktop a')).toHaveAttribute('href', '/app#accounts/open');
  await page.getByRole('button', { name: 'Open Account', exact: true }).click();
  await expect(page).toHaveURL(/#accounts\/open$/);
  const form = page.getByRole('form', { name: 'Open Account by ID' });
  const recipient = form.getByRole('combobox', { name: 'Recipient' });
  await recipient.fill('0xabcd');
  await recipient.press('Escape');
  await form.getByTestId('open-account-submit').click();
  await expect(form.getByRole('alert')).toHaveText('Full entity ID required (0x + 64 hex chars)');
  await recipient.fill(fixture.recovery.entityId);
  await recipient.press('Escape');
  await form.getByTestId('open-account-submit').click();
  await expect(form.getByRole('alert')).toHaveText('Cannot open account with yourself');
  if (testInfo.project.name === 'mobile-390x844') {
    const bounds = await form.getByRole('alert').boundingBox();
    const navigation = await page.getByRole('navigation', { name: 'Wallet navigation' }).boundingBox();
    if (!bounds || !navigation) throw new Error('DIRECT_OPEN_ERROR_BOUNDS_UNAVAILABLE');
    expect(bounds.y).toBeGreaterThanOrEqual(0);
    expect(bounds.y + bounds.height).toBeLessThan(navigation.y);
    const path = testInfo.outputPath('wallet-account-open-error-viewport.png');
    await page.screenshot({ animations: 'disabled', path });
    await testInfo.attach('direct-open-error-viewport', { contentType: 'image/png', path });
  }
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'wallet-account-open-self-error');
  await recipient.fill(`0x${'77'.repeat(32)}`);
  await expect(form.getByRole('alert')).toHaveCount(0);
  await recipient.press('Escape');
  await form.getByTestId('open-account-submit').click();
  await expect(form.getByRole('alert')).toContainText('ACCOUNT_DISPUTE_PARTY_ROLE_UNAVAILABLE');

  await recipient.fill('');
  const option = form.locator(`[role="option"][data-entity-id="${hubId}"]`);
  await expect(option).toBeVisible();
  await expect(form.getByRole('alert')).toHaveCount(0);
  await screenshotEvidence(page, testInfo, 'wallet-account-open-picker');
  await option.click();
  await expect(recipient).toHaveValue(hubId);
  await recipient.fill(`#${hubId.slice(2, 6)}`);
  await expect(form.locator('.wallet-entity-resolution')).toHaveText(hubId);
  await recipient.press('Escape');
  await screenshotEvidence(page, testInfo, 'wallet-account-open-recipient');
  await form.getByTestId('open-account-submit').click();
  await expect(form.getByRole('status')).toHaveText('Account request sent');
  await expect(recipient).toHaveValue('');
  const hub = page.locator(`[data-hub-entity-id="${hubId}"]`);
  await expect(hub).toHaveAttribute('data-connection-state', 'open', { timeout: 30_000 });
  await recipient.fill(hubId);
  await recipient.press('Escape');
  await form.getByTestId('open-account-submit').click();
  await expect(form.getByRole('status')).toHaveText('Account with this entity already exists');
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'wallet-account-open-committed');
  await page.getByRole('button', { name: '← Back to assets' }).click();
  await expect(page.getByLabel('Entity', { exact: true })).toHaveValue(fixture.recovery.entityId);
  await expect(page.locator('.account-rail-desktop a')).toHaveCount(6);
  await page.goBack();
  await expect(form).toBeVisible();
  await expect(hub).toHaveAttribute('data-connection-state', 'open');
  await page.goForward();
  await expect(page.getByRole('heading', { name: 'Assets & accounts' })).toBeVisible();
  expectNoBrowserErrors(errors);
});

test('direct Account opening reads the exact existing remote Account and keeps self rejection', async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  const fixture = await selectWalletFixtureRuntime(page);
  await page.goto('/app?portfolio=1', { waitUntil: 'domcontentloaded' });
  await page.getByLabel('Entity', { exact: true }).selectOption(fixture.entityId);
  await page.getByRole('button', { name: 'Open Account', exact: true }).click();
  const form = page.getByRole('form', { name: 'Open Account by ID' });
  const recipient = form.getByRole('combobox', { name: 'Recipient' });
  await recipient.fill(fixture.entityId);
  await recipient.press('Escape');
  await form.getByTestId('open-account-submit').click();
  await expect(form.getByRole('alert')).toHaveText('Cannot open account with yourself');
  await recipient.fill(fixture.counterpartyEntityId);
  await recipient.press('Escape');
  await form.getByTestId('open-account-submit').click();
  await expect(form.getByRole('status')).toHaveText('Account with this entity already exists');
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'wallet-account-open-remote-existing');
  expectNoBrowserErrors(errors);
});
