import { openWorkspaceStorageOrigin } from '../../browser-evidence';
import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from '../../browser-evidence';
import { screenshotGraphEvidence } from '../../graph-evidence';

test('operator Settings save exact local policies and retain them across panel reopen', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(90_000);
  const errors = observeBrowserErrors(page);
  await openWorkspaceStorageOrigin(page);
  await page.evaluate(() => {
    localStorage.setItem('xln-runtime-adapter-mode', 'embedded');
    localStorage.setItem('xln-workspace-layout', 'canonical-full-layout-sentinel');
  });
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await expect(settings.getByTestId('storage-wal-gib')).toBeVisible({ timeout: 45_000 });
  await expect(settings.getByTestId('storage-common-gib')).toHaveCount(0);
  await expect(settings.getByTestId('storage-history-gib')).toHaveCount(0);
  await expect(settings.getByTestId('storage-history-frames')).toHaveCount(0);
  await settings.getByTestId('storage-wal-gib').fill('0.0000000001');
  await settings.getByTestId('storage-limits-save').click();
  await expect(settings.getByRole('alert')).toHaveText('WAL epoch limit must be a positive GiB value with an exact byte count');
  await settings.getByTestId('storage-wal-gib').fill('2');
  await settings.getByTestId('storage-limits-save').click();
  await expect(settings.getByRole('status')).toContainText('Storage policy saved');
  await expect(settings.getByTestId('storage-wal-gib')).toHaveValue('2');
  await screenshotEvidence(page, testInfo, 'ops-settings-storage');
  await settings.getByRole('button', { name: 'Performance', exact: true }).click();
  await settings.getByTestId('perf-clone-mib').fill('1.25');
  await settings.getByTestId('perf-clone-ms').fill('0.000125');
  await settings.getByTestId('perf-reducer-ms').fill('5');
  await settings.getByTestId('perf-wal-ms').fill('25');
  await settings.getByTestId('perf-budgets-save').click();
  await expect(settings.getByRole('status')).toContainText('Performance budgets saved');
  await screenshotEvidence(page, testInfo, 'ops-settings-performance');
  await settings.getByRole('button', { name: 'Storage', exact: true }).click();
  await expect(settings.getByTestId('storage-wal-gib')).toHaveValue('2');
  await settings.getByTestId('storage-wal-gib').fill('');
  await settings.getByTestId('storage-limits-save').click();
  await expect(settings.getByRole('status')).toContainText('Storage policy saved');
  await page.locator('.dv-default-tab').filter({ hasText: /^Settings$/ }).locator('.dv-default-tab-action').click();
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  await expect(settings.getByTestId('storage-wal-gib')).toHaveValue('');
  await settings.getByRole('button', { name: 'Performance', exact: true }).click();
  await expect(settings.getByTestId('perf-clone-ms')).toHaveValue('0.000125');
  await expect(settings.getByTestId('perf-clone-mib')).toHaveValue('1.25');
  expect(await page.evaluate(() => localStorage.getItem('xln-workspace-layout'))).toBe('canonical-full-layout-sentinel');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('presentation config filters the real recording and applies caption and camera cues', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  const event = await page.evaluate(async () => {
    const moduleUrl = '/__app/ops/src/workspace/session/ops-workspace-playback.ts';
    const module = await import(moduleUrl);
    const selected = module.workspaceNetwork.get().selectedStep;
    return { runtimeId: selected.event.runtimeId, height: selected.event.height, timestamp: selected.event.timestamp };
  });
  const fullCount = Number(await timeline.getByLabel('Network frame', { exact: true }).getAttribute('max'));
  const changedCount = await page.evaluate(async () => {
    const moduleUrl = '/__app/ops/src/workspace/session/ops-workspace-playback.ts';
    const module = await import(moduleUrl);
    return module.workspaceNetwork.get().indexes.flatMap((index: { frames: { graphChanged: boolean }[] }) => index.frames).filter((frame: { graphChanged: boolean }) => frame.graphChanged).length;
  });
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await settings.getByRole('button', { name: 'Presentation', exact: true }).click();
  const draft = settings.getByRole('textbox', { name: 'Presentation config', exact: true });
  await draft.fill('{ invalid');
  await settings.getByRole('button', { name: 'Import presentation config', exact: true }).click();
  await expect(settings.getByRole('alert')).toContainText('NETWORK_MACHINE');
  const config = { version: 1, id: 'settings-browser', title: 'Operator presentation', timelineMode: 'all-frames', cues: [{
    id: 'final-state', at: event, title: 'Final payment state', subtitle: 'Shared presentation cue',
    camera: { position: { x: 10, y: 80, z: 300 }, target: { x: 10, y: 0, z: 0 }, fov: 65 },
  }] };
  await draft.fill(JSON.stringify(config));
  await settings.getByRole('button', { name: 'Import presentation config', exact: true }).click();
  await expect(settings.getByRole('status')).toContainText('Presentation config applied');
  await expect(timeline).toContainText('Final payment state');
  await settings.getByRole('button', { name: 'Camera', exact: true }).click();
  await settings.getByText('Current camera pose', { exact: true }).click();
  await expect.poll(async () => JSON.parse(await settings.getByTestId('settings-camera-pose').innerText()).position.z).toBe(300);
  await settings.getByRole('button', { name: 'Presentation', exact: true }).click();
  await settings.getByLabel('Timeline density', { exact: true }).selectOption('graph-changes');
  await expect(settings.getByRole('status')).toContainText('Presentation config applied');
  // AHB currently marks every recorded frame as graph-changing. Assert against
  // the real source flags, rather than assuming that this scenario must shrink.
  await expect(timeline.getByLabel('Network frame', { exact: true })).toHaveAttribute('max', String(changedCount - 1));
  await expect(draft).toHaveValue(/"timelineMode": "graph-changes"/);
  await expect(timeline.locator('output')).not.toHaveText('Live');
  await screenshotEvidence(page, testInfo, 'ops-settings-presentation');
  await settings.getByLabel('Timeline density', { exact: true }).selectOption('all-frames');
  await expect(settings.getByRole('status')).toContainText('Presentation config applied');
  await expect(timeline.getByLabel('Network frame', { exact: true })).toHaveAttribute('max', String(fullCount));
  await page.reload();
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  await expect(timeline).toContainText('Final payment state');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('recorded Settings control the retained scene and camera without editing Runtime policy', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000);
  const errors = observeBrowserErrors(page);
  await page.goto('/__app/ops/entity-workspace?scenario=ahb');
  const timeline = page.getByTestId('workspace-network-timeline');
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await timeline.getByLabel('Network frame', { exact: true }).press('End');
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await expect(settings.getByRole('status')).toContainText('Recorded scenarios and remote connections are read-only here.');
  await expect(settings.getByTestId('storage-limits-save')).toHaveCount(0);
  await settings.getByRole('button', { name: 'Scene', exact: true }).click();
  await settings.getByLabel('Grid opacity', { exact: true }).press('Home');
  for (let i = 0; i < 4; i++) await settings.getByLabel('Grid opacity', { exact: true }).press('ArrowRight');
  await settings.getByLabel('Grid divisions', { exact: true }).press('Home');
  for (let i = 0; i < 9; i++) await settings.getByLabel('Grid divisions', { exact: true }).press('ArrowRight');
  await settings.getByRole('checkbox', { name: 'Show xln guide' }).check();
  await expect(page.getByTestId('xln-mascot-toggle')).toBeVisible();
  await settings.getByRole('checkbox', { name: 'Show xln guide' }).uncheck();
  await expect(page.getByTestId('xln-mascot-toggle')).toHaveCount(0);
  await screenshotEvidence(page, testInfo, 'ops-settings-scene');
  await settings.getByRole('button', { name: 'Camera', exact: true }).click();
  await settings.getByLabel('Camera target x', { exact: true }).fill('10');
  await settings.getByLabel('Camera distance', { exact: true }).press('Home');
  for (let i = 0; i < 10; i++) await settings.getByLabel('Camera distance', { exact: true }).press('ArrowRight');
  await settings.getByLabel('Field of view', { exact: true }).press('Home');
  for (let i = 0; i < 6; i++) await settings.getByLabel('Field of view', { exact: true }).press('ArrowRight');
  await settings.getByText('Current camera pose', { exact: true }).click();
  await expect.poll(async () => JSON.parse(await settings.getByTestId('settings-camera-pose').innerText()).target.x).toBe(10);
  await expect.poll(async () => Math.round(JSON.parse(await settings.getByTestId('settings-camera-pose').innerText()).distance)).toBe(600);
  await settings.getByRole('button', { name: 'Focus origin', exact: true }).click();
  await expect(settings.getByLabel('Camera target x', { exact: true })).toHaveValue('0');
  await screenshotEvidence(page, testInfo, 'ops-settings-camera');
  await settings.getByRole('button', { name: 'Performance', exact: true }).click();
  await settings.getByRole('checkbox', { name: 'Show FPS and render stats', exact: true }).check();
  await page.getByRole('button', { name: 'Open Graph3D panel', exact: true }).click();
  await page.getByTestId('workspace-graph').getByRole('button', { name: 'Fit network' }).click();
  await expect(page.getByTestId('graph-render-stats')).toContainText('draw calls');
  await screenshotGraphEvidence(page, testInfo, 'ops-settings-graph-applied');
  await page.reload();
  await expect(timeline.locator('output')).toContainText('1/', { timeout: 90_000 });
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  await settings.getByRole('button', { name: 'Scene', exact: true }).click();
  await expect(settings.getByLabel('Grid opacity', { exact: true })).toHaveValue('0.2');
  await settings.getByRole('button', { name: 'Camera', exact: true }).click();
  await expect(settings.getByLabel('Field of view', { exact: true })).toHaveValue('60');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('effect, renderer and XR controls retain one exact view-settings record', { tag: '@functional' }, async ({ page }) => {
  const errors = observeBrowserErrors(page);
  await openWorkspaceStorageOrigin(page);
  await page.evaluate(() => localStorage.setItem('xln-runtime-adapter-mode', 'embedded'));
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await settings.getByRole('button', { name: 'Effects', exact: true }).click();
  await settings.getByRole('checkbox', { name: 'Enable lightning animation', exact: true }).check();
  await settings.getByLabel('Lightning duration (ms)', { exact: true }).fill('330');
  await settings.getByRole('checkbox', { name: 'Enable jurisdiction broadcast', exact: true }).uncheck();
  await settings.getByRole('radio', { name: 'wave', exact: true }).check();
  await settings.getByRole('button', { name: 'Performance', exact: true }).click();
  await settings.getByLabel('XR graph scale', { exact: true }).fill('1.75');
  await settings.getByLabel('Renderer', { exact: true }).selectOption('webgpu');
  await page.locator('.dv-default-tab').filter({ hasText: /^Settings$/ }).locator('.dv-default-tab-action').click();
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  await settings.getByRole('button', { name: 'Effects', exact: true }).click();
  await expect(settings.getByRole('checkbox', { name: 'Enable lightning animation', exact: true })).toBeChecked();
  await expect(settings.getByLabel('Lightning duration (ms)', { exact: true })).toHaveValue('330');
  await expect(settings.getByRole('checkbox', { name: 'Enable jurisdiction broadcast', exact: true })).not.toBeChecked();
  await expect(settings.getByRole('radio', { name: 'wave', exact: true })).toBeChecked();
  await settings.getByRole('button', { name: 'Performance', exact: true }).click();
  await expect(settings.getByLabel('XR graph scale', { exact: true })).toHaveValue('1.75');
  await expect(settings.getByLabel('Renderer', { exact: true })).toHaveValue('webgpu');
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('xln-view-settings') || 'null'))).toMatchObject({
    lightningEnabled: true, lightningSpeed: 330, broadcastEnabled: false,
    broadcastStyle: 'wave', rendererMode: 'webgpu', vrScaleMultiplier: 1.75,
  });
  expectNoBrowserErrors(errors);
});


test('Stack Manager inspects the real daemon signer and exact RPC, rejects failures and clears stale probes', { tag: '@resilience' }, async ({ page }, testInfo) => {
  const { installImportedRuntime, readWalletRuntimeFixture } = await import('../../wallet/fixtures/wallet-runtime-test-helpers');
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await settings.getByRole('button', { name: 'Stack Manager', exact: true }).click();
  const stack = settings.getByTestId('workspace-stack-manager');
  await expect(stack.getByTestId('stack-manager-phase')).toHaveText('Deployment phase: idle');
  const signer = await stack.getByTestId('stack-manager-signer').inputValue();
  expect(signer).toMatch(/^0x[0-9a-f]{40}$/);
  await stack.getByTestId('stack-manager-rpc').fill(fixture.recovery.rpcUrl);
  await stack.getByRole('button', { name: 'Probe RPC', exact: true }).click();
  await expect(stack.getByTestId('stack-manager-probe')).toContainText(fixture.recovery.rpcUrl);
  await expect(stack.getByTestId('stack-manager-probe')).toContainText(signer);
  await stack.getByTestId('stack-manager-probe').scrollIntoViewIfNeeded();
  await screenshotEvidence(page, testInfo, 'ops-settings-stack-manager-probe');
  expectNoBrowserErrors(errors);
  await stack.getByTestId('stack-manager-rpc').fill('file:///invalid-rpc');
  await expect(stack.getByTestId('stack-manager-probe')).toHaveCount(0);
  await stack.getByRole('button', { name: 'Probe RPC', exact: true }).click();
  await expect(stack.getByRole('alert')).toHaveText('STACK_MANAGER_STATUS_HTTP_400');
  await screenshotEvidence(page, testInfo, 'ops-settings-stack-manager-error');
  expect(errors.pageErrors).toEqual([]);
  expect(errors.consoleErrors).toEqual(['Failed to load resource: the server responded with a status of 400 (Bad Request)']);
  await stack.getByRole('button', { name: 'Refresh Runtime signers', exact: true }).click();
  await expect(stack.getByTestId('stack-manager-phase')).toBeVisible();
  await expect(stack.getByRole('alert')).toHaveCount(0);
  await settings.getByRole('button', { name: 'Scene', exact: true }).click();
  await settings.getByRole('button', { name: 'Stack Manager', exact: true }).click();
  await expect(stack.getByTestId('stack-manager-phase')).toBeVisible();
  await expect(stack.getByTestId('stack-manager-rpc')).toHaveValue('');
  await expect(stack.getByTestId('stack-manager-probe')).toHaveCount(0);
  expect(await stack.innerText()).not.toContain(fixture.token);
  await expectPageContained(page);
});

test('Stack Manager deploys, verifies, registers, and shares one real isolated V1 stack', { tag: '@functional' }, async ({ page }, testInfo) => {
  testInfo.setTimeout(180_000);
  const { installImportedRuntime, readStackManagerRpcFixture, readWalletRuntimeFixture } = await import('../../wallet/fixtures/wallet-runtime-test-helpers');
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  const deploymentRpc = await readStackManagerRpcFixture(page);
  const suffix = testInfo.project.name.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  const name = `Ops deployed ${suffix}`;
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  const settings = page.getByTestId('workspace-settings');
  await settings.getByRole('button', { name: 'Stack Manager', exact: true }).click();
  const stack = settings.getByTestId('workspace-stack-manager');
  await expect(stack.getByTestId('stack-manager-phase')).toBeVisible();
  await stack.getByTestId('stack-manager-rpc').fill(deploymentRpc.rpcUrl);
  await stack.getByRole('button', { name: 'Probe RPC', exact: true }).click();
  await expect(stack.getByTestId('stack-manager-probe')).toContainText('Native balance (wei)');
  await stack.getByTestId('stack-manager-name').fill(name);
  await stack.getByTestId('stack-manager-stablecoin').selectOption('test');
  await stack.getByTestId('stack-manager-confirmations').fill('1');
  await stack.getByTestId('stack-manager-confirm').check();
  await expect(stack.getByTestId('stack-manager-deploy')).toBeEnabled();
  await stack.getByTestId('stack-manager-deploy').click();
  const result = stack.getByTestId('stack-manager-result');
  await expect(result).toContainText(`${name} deployed and registered`, { timeout: 150_000 });
  await expect(result).toContainText('publication local/not_requested');
  await expect(stack.getByLabel('Configured jurisdiction stack', { exact: true })).toHaveValue(name);
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('xln-jmachines') || 'null'));
  expect(persisted.activeJMachine).toBe(name);
  expect(persisted.configs.find((entry: { name: string }) => entry.name === name)?.contracts.entityProvider).toMatch(/^0x[0-9a-fA-F]{40}$/);
  await screenshotEvidence(page, testInfo, 'ops-settings-stack-manager-deployed');
  await stack.getByTestId('stack-manager-confirm').check();
  await stack.getByTestId('stack-manager-deploy').click();
  await expect(stack.getByRole('alert')).toHaveText('STACK_MANAGER_DEPLOY_HTTP_400', { timeout: 15_000 });
  await expectPageContained(page);
  expect(errors.pageErrors).toEqual([]);
  expect(errors.consoleErrors).toEqual(['Failed to load resource: the server responded with a status of 400 (Bad Request)']);
});

test('Stack Manager does not inspect a daemon from an in-browser Runtime', { tag: '@functional' }, async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  await openWorkspaceStorageOrigin(page);
  await page.evaluate(() => localStorage.setItem('xln-runtime-adapter-mode', 'embedded'));
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Settings panel', exact: true }).click();
  await page.getByTestId('workspace-settings').getByRole('button', { name: 'Stack Manager', exact: true }).click();
  const stack = page.getByTestId('workspace-stack-manager');
  await expect(stack.getByRole('status')).toContainText('Stack Manager requires a daemon Runtime.');
  await expect(stack.getByRole('button', { name: 'Probe RPC', exact: true })).toHaveCount(0);
  await screenshotEvidence(page, testInfo, 'ops-settings-stack-manager-embedded');
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});
