import { openWorkspaceStorageOrigin } from '../../browser-evidence';
import { expect, test, type WebSocket } from '@playwright/test';

import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from '../../browser-evidence';
import { installImportedRuntime, readWalletRuntimeFixture } from '../../wallet/fixtures/wallet-runtime-test-helpers';

test('Entity panels keep independent selection, navigation and history on one real Runtime connection', async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await openWorkspaceStorageOrigin(page);
  await installImportedRuntime(page, fixture);
  const sockets: WebSocket[] = [];
  page.on('websocket', socket => { if (socket.url() === fixture.wsUrl) sockets.push(socket); });
  await page.goto('/__app/ops/entity-workspace#accounts');
  const primary = page.locator('.workspace-entity-pane:not([data-entity-id])');
  await expect(primary.getByTestId('entity-workspace-shell')).toHaveAttribute('data-read-status', 'ready');
  const primaryEntity = await primary.getByTestId('entity-workspace-shell').getAttribute('data-entity-id');
  if (!primaryEntity) throw new Error('PRIMARY_ENTITY_REQUIRED');
  const peerEntityId = primaryEntity === fixture.entityId ? fixture.counterpartyEntityId : fixture.entityId;
  await page.getByRole('button', { name: 'Open Gossip panel' }).click();
  const directory = page.getByTestId('runtime-gossip-panel');
  await directory.getByRole('searchbox').fill(peerEntityId);
  const peerTitle = await directory.locator('article strong').innerText();
  await directory.getByRole('button', { name: /^Open Entity / }).click();
  const peer = page.locator(`.workspace-entity-pane[data-entity-id="${peerEntityId}"]`);
  await expect(peer.getByTestId('entity-workspace-shell')).toHaveAttribute('data-read-status', 'ready');
  await expect(peer.getByTestId('entity-workspace-shell')).toHaveAttribute('data-entity-id', peerEntityId);
  await peer.getByTestId('entity-workspace-tab-settings').click();
  await peer.getByRole('link', { name: 'Display', exact: true }).click();
  await peer.getByRole('checkbox', { name: /Time Machine/i }).check();
  const input = peer.getByTestId('time-machine-remote-height');
  const latest = Number(await input.getAttribute('max'));
  expect(latest).toBeGreaterThan(1);
  await input.fill(String(latest - 1));
  await peer.getByTestId('time-machine-remote-scan-button').click();
  await expect(peer.getByTestId('entity-workspace-time-machine')).toHaveAttribute('data-mode', 'history');
  await expect(peer.getByTestId('time-machine-mode')).toHaveText(`History · h${latest - 1}`);
  expect(new URL(page.url()).hash).toBe('#accounts');
  await page.getByRole('button', { name: 'Open Entity panel', exact: true }).click();
  await expect(primary.getByTestId('entity-workspace-shell')).toHaveAttribute('data-active-tab', 'accounts');
  await expect(primary.getByTestId('entity-workspace-shell')).toHaveAttribute('data-entity-id', primaryEntity);
  await expect(primary.getByTestId('entity-workspace-time-machine')).toHaveAttribute('data-mode', 'live');
  expect(sockets).toHaveLength(1);
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-independent-entity-panels');
  await page.getByRole('button', { name: 'Open Gossip panel' }).click();
  await directory.getByRole('button', { name: /^Open Entity / }).click();
  await expect(peer).toHaveCount(1);
  await expect(peer.getByTestId('entity-workspace-time-machine')).toHaveAttribute('data-mode', 'history');
  const tab = page.locator('.dv-default-tab').filter({ hasText: peerTitle });
  await tab.locator('.dv-default-tab-action').click();
  await expect(peer).toHaveCount(0);
  await page.getByRole('button', { name: 'Open Entity panel', exact: true }).click();
  await expect(primary.getByTestId('entity-workspace-shell')).toHaveAttribute('data-read-status', 'ready');
  expect(sockets).toHaveLength(1);
  await openWorkspaceStorageOrigin(page);
  await expect.poll(async () => {
    const response = await page.request.get(fixture.wsUrl.replace('ws:', 'http:').replace('/rpc', '/connections'));
    const result: unknown = await response.json();
    if (!result || typeof result !== 'object' || !('active' in result)) throw new Error('FIXTURE_CONNECTION_COUNT_INVALID');
    return result.active;
  }).toBe(0);
  expectNoBrowserErrors(errors);
});
