import { expect, test } from '@playwright/test';
import { expectNoBrowserErrors, expectPageContained, observeBrowserErrors, screenshotEvidence } from '../../browser-evidence';
import { readWalletRuntimeFixture } from '../../wallet/fixtures/wallet-runtime-test-helpers';

test('visible Runtime attach and selection update existing panels without restarting the browser Runtime', async ({ page }, testInfo) => {
  testInfo.setTimeout(90_000);
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await page.goto('/__app/ops/entity-workspace');
  const openManager = () => page.getByRole('button', { name: 'Open Runtimes panel', exact: true }).click();
  await openManager();
  const manager = page.getByTestId('remote-runtime-manager');
  await manager.getByRole('button', { name: 'Use browser Runtime', exact: true }).click();
  await expect(manager.locator('.ops-selected-runtime')).toContainText('embedded', { timeout: 45_000 });
  const localId = await manager.locator('.ops-selected-runtime').innerText();
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  await expect(page.getByLabel('Console command')).toBeVisible();
  await openManager();
  await manager.getByLabel('Label', { exact: true }).fill('Fixture owner');
  await manager.getByLabel('WebSocket endpoint').fill(fixture.wsUrl);
  await manager.getByLabel('Admin capability token').fill(fixture.token);
  await manager.getByRole('button', { name: 'Validate & attach', exact: true }).click();
  await expect(manager.getByRole('status')).toHaveText('Attached 1/1');
  await expect(manager.locator('.ops-selected-runtime')).toContainText(fixture.runtimeId);
  await expect(manager.getByLabel('Admin capability token')).toHaveValue('');
  await page.getByRole('button', { name: 'Open Entity panel', exact: true }).click();
  await expect(page.getByTestId('entity-workspace-shell')).toHaveAttribute('data-runtime-id', fixture.runtimeId);
  await expect(page.getByTestId('entity-workspace-shell')).toHaveAttribute('data-read-status', 'ready');
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  await expect(page.getByTestId('workspace-console')).toContainText('This panel requires a local Runtime.');
  await openManager();
  await screenshotEvidence(page, testInfo, 'ops-runtime-attached');
  await manager.getByRole('button', { name: 'Use browser Runtime', exact: true }).click();
  await expect(manager.locator('.ops-selected-runtime')).toHaveText(localId);
  await expect(manager.getByRole('status')).toHaveText('Runtime selected');
  await page.getByRole('button', { name: 'Open Console panel', exact: true }).click();
  await expect(page.getByLabel('Console command')).toBeVisible();
  await openManager();
  await manager.getByRole('button', { name: 'Select Fixture owner', exact: true }).click();
  await expect(manager.locator('.ops-selected-runtime')).toContainText(fixture.runtimeId);
  await expectPageContained(page);
  expectNoBrowserErrors(errors);
});

test('Runtime Manager exposes expiry, retry and bulk validation using real fixture capabilities', async ({ page }, testInfo) => {
  const errors = observeBrowserErrors(page);
  const fixture = await readWalletRuntimeFixture(page);
  await page.goto('/__app/ops/entity-workspace');
  await page.getByRole('button', { name: 'Open Runtimes panel', exact: true }).click();
  const manager = page.getByTestId('remote-runtime-manager');
  const token = fixture.token.split('.'); token[2] = '1';
  await manager.getByLabel('Label', { exact: true }).fill('Expired');
  await manager.getByLabel('WebSocket endpoint').fill(fixture.wsUrl);
  await manager.getByLabel('Admin capability token').fill(token.join('.'));
  await manager.getByRole('button', { name: 'Validate & attach', exact: true }).click();
  await expect(manager.getByRole('alert')).toContainText('expired');
  await manager.getByRole('button', { name: 'Retry failed (1)', exact: true }).click();
  await expect(manager.getByRole('alert')).toContainText('expired');
  await screenshotEvidence(page, testInfo, 'ops-runtime-expired');
  await manager.getByRole('button', { name: 'Bulk', exact: true }).click();
  await manager.getByLabel('Runtime import list').fill(`First | admin | ${fixture.wsUrl} | ${fixture.token}\nSecond | admin | ${fixture.wsUrl} | ${fixture.token}`);
  await manager.getByRole('button', { name: 'Validate & attach', exact: true }).click();
  await expect(manager.getByRole('status')).toHaveText('Attached 2/2');
  await expect(manager.locator('[data-status="connected"]')).toHaveCount(2);
  await expect(manager.getByRole('alert')).toHaveCount(0);
  await expect(manager.getByLabel('Runtime import list')).toHaveValue('');
  await expectPageContained(page);
  await screenshotEvidence(page, testInfo, 'ops-runtime-bulk');
  expectNoBrowserErrors(errors);
});
